osmlab/atlas-checks

- src/main/java/org/openstreetmap/atlas/checks/flag/CheckFlag.java
- src/main/java/org/openstreetmap/atlas/checks/flag/FlaggedObject.java
- src/test/java/org/openstreetmap/atlas/checks/flag/CheckFlagTest.java
- src/test/java/org/openstreetmap/atlas/checks/flag/CheckFlagTestRule.java
`CheckFlag` fails to serialize because `challengeName` member is of `Optional` type - not serializable. This PR makes `CheckFlag` fully serializable by removing `Optional` wrapper around `challengeName` value. 
To test this change I created `CheckFlagTest` class. I serialized and deserialized several `CheckFlag` instances. While doing that, I realized that `equals` method in `CheckFlag` was just for equality between identifiers. I updated that method to include other class members in equality check. Also updated `hashCode` method and made it consistent with `equals` method.
Equality check in `CheckFlag` was checking for equality between `FlaggedObject` instances. I implemented `equals` and `hashCode` methods there to make sure we are not failing equality because of references, but we rely …
> Make CheckFlag serializable

- src/main/java/org/openstreetmap/atlas/checks/validation/tag/AbbreviatedNameCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/AbbreviatedNameCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/AbbreviatedNameCheckTestRule.java
This PR introduces `AbbreviatedNameCheck` to check if `name` tag has any abbreviations in it. [OSM wiki page](http://wiki.openstreetmap.org/wiki/Names#Abbreviation_.28don.27t_do_it.29) clearly says not using any abbreviations.
I implemented the check in a way so that we can use configuration to provide `locale` and `abbreviations` as a list. Atlas object's name will be fetched, lowercased and then split into tokens. Each token will be tested against set of abbreviations. If token matches to an abbreviation, then object will be flagged.
Here is a sample configuration to check for abbreviations in names with English locale:
```
{
"locale": "en",
"abbreviations": ["ave", "st", "dr", "ne", "cir", "pl", "apt"]
}
```
> Add AbbreviatedNameCheck

- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionTestCaseRule.java
Updating this check to account for valid intersections between roads and buildings that were being flagged. Specifically, now ignoring intersection when building=roof or tunnel=building_passage. In addition, this update ignores intersection when a Edge approaches a building, intersects at one single point at the end of the Edge, and then continues through the building with proper tagging (e.g.
Toll booths).
> Updating the BuildingRoadIntersectionCheck 

- src/main/java/org/openstreetmap/atlas/checks/persistence/SparkFileHelper.java
- src/test/java/org/openstreetmap/atlas/checks/persistence/SparkFileHelperTest.java
This PR adds two helper methods `isDirectory` and `list` to `SparkFileHelper` class. These methods would be useful to check is a given path is directory or not and for directories list resources under.
> Add two helper methods: isDirectory and list

- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/persistence/SparkFileHelper.java
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/PoolSizeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutClosedLoopCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SnakeRoadCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/DuplicateNodeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/OrphanNodeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidTurnRestrictionCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/AbbreviatedNameCheck.java
- src/test/java/org/openstreetmap/atlas/checks/base/checks/BaseTestCheck.java
- src/test/java/org/openstreetmap/atlas/checks/base/checks/CheckResourceLoaderTestCheck.java
- src/test/java/org/openstreetmap/atlas/checks/base/checks/PierTestCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheckTest.java
An example configuration
```
"BuildingRoadIntersectionCheck":
{
"enabled":true,
"locale":"es",
"flags":{
"en":["Building (id-{0}) intersects road (id-{1})"],
"es":["Edificio(id-{0}) cruza calle(id-{1})"]
}
}
```
Results in Instructions like:
"1. Edificio(id-465465839) cruza calle(id-443627253)"
Where a configuration like this:
```
"BuildingRoadIntersectionCheck":
{
"enabled":true,
"locale":"en",
"flags":{
"en":["Building (id-{0}) intersects road (id-{1})"],
"es":["Edificio(id-{0}) cruza calle(id-{1})"]
}
}
```
If no flags are provided in the configuration then `getLocalizedInstruction(int, Object…)` in BaseCheck will return the instruction provided by `getFallbackInstructructions()`. If a specific language set of instructions does not have all instructions then the fallback instructions …
> Adding instruction localization for Atlas Check Flags

- src/main/java/org/openstreetmap/atlas/checks/validation/areas/PoolSizeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SnakeRoadCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/DuplicateNodeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/OrphanNodeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidTurnRestrictionCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/AbbreviatedNameCheck.java
MessageFormat by default formats all `long` types with comma seperated thousands, which is an incorrect representation of an OSM ID. Changed the instruction formats to specify the formatting of any OSM IDs.
> Fixed ID formatting

- config/configuration.json
- dependencies.gradle
- docs/checks/sharpAngleCheck.md
- docs/debugging.md
- docs/dev.md
- docs/unit_tests.md
- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Survey.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/serializer/ChallengeDeserializer.java
- src/main/java/org/openstreetmap/atlas/checks/persistence/SparkFileHelper.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheck.java
- src/main/resources/log4j.properties
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionTestCaseRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsTestCaseRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheckTestRule.java
Also updating MapRoulette functions to allow the use of tags when creating challenges. Updating documents to describe how to develop and debug Atlas-Checks.
SignPostCheck will check is to help identify segments that are missing the proper tagging for sign posts. 
IntersectingBuildingsCheck will, much as the name indicates, flag buildings that intersect with each other.
The documentation includes how to debug Checks that you create, as well has help for writing unit tests for you your newly created Checks.
> Adding new SignPostCheck and IntersectingBuildingsCheck. 

- LICENSE
- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/test/java/org/openstreetmap/atlas/checks/base/CheckResourceLoaderTest.java
The PR utilizes keyword overrides to create per country/group configuration options. The check resource loader initializes a set of checks for every country using a configuration specific to the countries overrides and the groups overrides.
The new group interaction can be found as an example below
```
{
"CheckResourceLoader.scanUrls": ["org.openstreetmap.atlas.checks.base.checks"],
"groups":{
"beginningAlphabet":["ABC","DEF"],
"alphabetEnds":["ABC","XYZ"]
},
"CheckResourceLoaderTestCheck":{
"enabled": true,
"var1":1,"var2":"Hi",
"override.beginningAlphabet.var1":2,
"override.alphabetEnds.var2":"Bye"
}
}
```
The above configuration will override var1 for ABC and DEF, and var2 for ABC and XYZ. The test can be found in the PR.
**Dependent on https://github.com/osmlab/atlas/pull/77**
> Configuration overrides for countries and groups of countries in Integrity Checks

- src/main/java/org/openstreetmap/atlas/checks/validation/tag/UnusualLayerTagsCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/UnusualLayerTagsCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/UnusualLayerTagsCheckTestRule.java
The "UnusualLayerTagCheck” is intended to validate layer tag values when accompanied by tunnel and bridge tags.
The check is implemented using the following rules:
1. Layer tag value should be an integer, ranging from -5 to 5, excluding 0 
2. Ways passed above other Ways with valid layer tag (above), accompanied by the bridge* *tag containing one of the following values:
- YES, VIADUCT, AQUEDUCT, BOARDWALK, MOVABLE, SUSPENSION, CULVERT, ABANDONED, LOW_WATER_CROSSING, SIMPLE_BRUNNEL, COVERED
3. Ways passed above other Ways with valid layer tag, accompanied by a tunnel tag containing one of the following values:
- YES, CULVERT, BUILDING_PASSAGE 
4. Ways with junction=ROUNDABOUT tag must not contain layer tag
> Adding new Check: UnusualLayerTagCheck

- src/main/java/org/openstreetmap/atlas/checks/flag/CheckFlag.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheckTestRule.java
This PR updates `SignPostCheck` for flexibility and easier maintenance. In addition to off ramps, now on ramps are flagged as well. However, on-ramps are treated differently and their start location is found and flagged rather than where they connect to highway.
- Check logic is now driven by configuration. That makes it flexible. Any additional highway types could be added, or existing ones could be ignored without a code change.
- I removed additional `missingTags` and `offendingObjects` sets that were used to track objects and tags. I am now relying on `CheckFlag` class directly. At the end, if instance doesn't have anything flagged, we'll skip flag operation.
- While doing this I hit a bug in `CheckFlag` class. Methods `addObject` and `addObjects` had different behavior. I updated …
> Update SignPostCheck with off/on ramp specific logic

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolyLineCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineTestCaseRule.java
The main goal of this PR is to improve the clarity of flags by classifying various cases of self-intersection.
- Line features w/ building tags
- Area features w/ duplicate Edges
- Area features w/ invalid geometries 
- Roads w/ invalid geometries
This also removes all flags containing following tags Highway tags: _PROPOSED, CONSTRUCTION, FOOTWAY, PATH_, as well as all Waterway tags.
> SelfIntersectingPolylineCheck enhancements

- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
This pull request serves to add Complex Entity support in the Spark Integrity Job class. Without this functionality, the Spark Integrity Job will not pick up Complex Entities. Examples of ComplexEntity objects include BigNode, ComplexIsland etc.
> Spark Integrity Job Complex Entity Support

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SnakeRoadCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/DuplicateNodeCheck.java
This PR has minor updates for three checks.
- `Iterable` used in `FloatingEdgeCheck` is cached first before being consumed. Otherwise, `for` loop goes and repeatedly goes over it.
- `!edge.connectedEdges().isEmpty()` condition is removed from `SnakeRoadCheck`, because that is redundant. `SnakeRoadNetworkWalk` already handles edges with no connections (such cases are very rare anyways).
- `DuplicateNodeCheck` was relying on `nodesWithin` call, but there is already `nodesAt` call that could be used to get nodes at a given location. Therefore, `nodesWithin` is replaced with `nodesAt`. Also `isFlagged` check is moved into `validCheckForObject`. Finally, node identifiers are collected and used in the instruction for easier action (there could be more than 1 duplicate).
Changes are tested, …
> Integrity check updates

- docs/checks/addressPointMatch.md
- src/main/java/org/openstreetmap/atlas/checks/validation/points/AddressPointMatchCheck.java
This pull request fixes two issues with the Address Point Match check:
1. A null pointer exception associated with checking for the Associated Street relation in the `hasAssociatedStreetRelation()` method
2. Adds back a conditional to the `validCheckForObject()` method which checks that the point contains a AddressHouseNumber tag (this conditional was accidentally removed in code review)
Associated documentation was also updated.
> Address Point Match Check Bug Fix

- config/configuration.json
- docs/checks/oneMemberRelationCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
The OneMemberRelation Check flags Relations that only have one Member.
This pull request contains logic, documentation, configuration, and unit tests.
OSM Examples:
https://www.openstreetmap.org/relation/6077987
https://www.openstreetmap.org/relation/7214599
> One Member Relation Check

- .gitignore
- README.md
- docs/dev.md
- docs/standalone.md
- gradle/wrapper/gradle-wrapper.properties
Hey!
I just got atlas checks running on my machine, and I have a small detail in the README that explains that the user does indeed need to put a PBF in the data dir. Also, I updated the gradlew, which pointed to a very old gradle. This way, users can call gradlew and be assured that it will be using the version of gradle we intend.
cc/ @savannahostrowski
> Update README and gradlew

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
The `traffic.countries.left` configuration value was causing a error when used. Fixed by changing the default value and `leftDrivingCountries` variable to a `List<String>`.
> MalformedRoundabout Configuration Bug

- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
When creating a Challenge, the `defaultPriority` property in MapRoulette's `POST: /api/challenge` endpoint requires an integer. However, when `defaultPriority` is not defined in each check's challenge configuration, the `ChallengePriority.NONE` default value never gets converted into an integer (-1). Causing the following error:
```
{
"status": "KO",
"message": {
"obj.defaultPriority": [
{
"msg": [
"error.expected.jsnumber"
],
"args": []
}
]
}
}
```
> Converting all MR Challenge defaultPriority values to integers

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionTestCaseRule.java
The Building Road Intersection (BRI) integrity check is meant to analyze overlap between roads and buildings. Barring exceptions for certain scenarios, the geometry for a road and that for a building’s boundary are not supposed to intersect each other.
This PR depends on Atlas PR [#110](https://github.com/osmlab/atlas/pull/110) for the AmenityTag.PARKING_ENTRANCE enum, and Atlas PR [#121](https://github.com/osmlab/atlas/pull/121) for the EntranceTag.java functionality.
**Added functionality:**
- Ignore tag amenity=parking
- Ignore roads/buildings who intersect at a Node which is labeled Parking Garage Entrance/Exit or entrance=yes
- Ignore tag area=yes
- Ignore tag indoor=yes
- Ignore tag tunnel=yes
- Ignore tag highway=service when intersecting building with tag amenity=fuel
- Ignore …
> Building Road Intersection Enhancements

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsTestCaseRule.java
The enhancements made to the Intersecting Building check rework the way an overlap is defined. Previously an overlap was defined by having one area completely surrounding or matching another. Now overlap is defined as areas of the exact same dimensions. Intersections where one area surrounds another are now defined as 'contains'.
The configurable overlap.lower.limit was removed to accommodate this change. It is now a static 1.0, or complete area match.
> Intersecting Building Check Enhancments

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheckTestRule.java
This enhancement changes the default threshold.degrees, and adds unit tests.
The default threshold.degrees was changed from 149 to 97. This appears to catch about 3 times more true positive cases, without adding any false positives.
> Sharp Angle Check Enhancement

- config/configuration.json
- dependencies.gradle
- docs/checks/conflictingAreaTagCombination.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/ConflictingAreaTagCombination.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/ConflictingAreaTagCombinationCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/ConflictingAreaTagCombinationCheckTestRule.java
This check flags mutually exclusive tag combinations on Atlas Area objects.
This PR includes check code, config, tests & documentation..
For live examples, see: https://github.com/danielduhh/atlas-checks/blob/dev-cat/docs/checks/conflictingAreaTagCombination.md#live-example
> Conflicting Area Tag Combination check

- config/configuration.json
- docs/checks/invalidLanesTagCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheckTestRule.java
This check flags Edges where there is a `lanes` tag with an abnormal value. 
Abnormal values are defined as anything not in the configurable `lanes.filter`.  
The default values are set as `1,1.5,2,3,4,5,6,7,8,9,10`. 
Toll booth plazas are ignored, as they often have an abnormally high number of lanes. 
**OSM Examples:**
1. Way [id:156825478](https://www.openstreetmap.org/way/156825478) is flagged correctly by this check as a highway with no lanes.
2. Way [id:247311654](https://www.openstreetmap.org/way/247311654) is connected to a toll booth and has a high but valid number of lanes. It is not flagged.
> Invalid Lanes Tag Check

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheckTestRule.java
This enhancement changes default configurable values, removes the `motorway_junction` test from on ramps, reworks the `findFirstRampEdge` method, and enables this check.  
The new default values create less errors from overlapping values.
The `motorway_junction` test was removed from on ramps because they do not require a node with that tag: [OSM wiki: motorway_junction](https://wiki.openstreetmap.org/wiki/Tag:highway=motorway_junction)
`findFirstRampEdge` no longer uses heading to determine connection. It now uses a recursive search for arterial roads based on the configurable filters and minimum arterial classification. 
This check was disabled via the configuration. The configuration.json in this PR re-enables it.
> Sign Post Check Enhancement

- config/configuration.json
- docs/checks/streetNameIntegersOnlyCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/StreetNameIntegersOnlyCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/StreetNameIntegersOnlyCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/StreetNameIntegersOnlyCheckTestRule.java
This check flags edges that have only integers in their name. 
An example of an improper name tag in this case is something like: `name=42`  
Items like `name=1st Ave` are allowed, and not flagged.
Multiple variations of the name tag can be checked by adding their tag key to the configurable `name_keys.filter`. Default values are:
* name
* name:left
* name:right
**OSM Example:**
1. The way [id:395169730](https://www.openstreetmap.org/way/395169730) is a road and has the name 1543 (an integer).
> Street Name Integers Only Check

- config/configuration.json
This updates a typo in the `IntersectingBuildingsCheck` configuration.
> IntersectingBuildingsCheck config typo

- config/configuration.json
- docs/checks/mixedCaseNameCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheckTestRule.java
This check flags objects with name tags that improperly use mixed cases.
Proper case use is defined by set standards and configurable exceptions. 
The standards are as follows:
* Words must start with a capital unless:
* The first letter is preceded by a number
* All the words in the name are lower case
* All other letters must be lower case unless: 
* They follow an apostrophe and, they are not the last letter of the word
* The entire word is uppercase, except the last letter if it follows or is followed by an apostrophe
The standards are broken by the following configurable exceptions (with default values):
* Articles that are capitalised only if they are the first word:
* a, an, the
* Prepositions that do not need to start with a capital:
* and, from, to, of, by, upon, on, off, at, as, …
> Mixed Case Name Check

- src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
This enhancement is to fix an issue where flags with empty geometries were being created. This was occurring when a relation with another relation as its only member was flagged. 
Now in these situations the geometry of the nested relations is recursively gathered, to show what the relation represents, and the situation is noted in the instruction.
> One Member Relation Enhancement

- src/main/java/org/openstreetmap/atlas/checks/event/EventService.java
- src/test/java/org/openstreetmap/atlas/checks/event/EventServiceTest.java
Allow functionality to unregister processors you no long want on the event bus.
> Unregister processor on the event service

- .travis.yml
This fixes https://github.com/osmlab/atlas/issues/242 for the atlas-checks project. (Similar to https://github.com/osmlab/atlas/pull/245)
Use sudo=false and dist=trusty in builds. That solves the issue as per https://github.com/travis-ci/travis-ci/issues/9555#issuecomment-413187047
N/A
N/A
------
In doubt: [Contributing Guidelines](https://github.com/osmlab/atlas/blob/dev/CONTRIBUTING.md)
> Use trusty and sudo false for Travis

- src/main/java/org/openstreetmap/atlas/checks/event/EventService.java
Unregister all processors on the EventBus after complete is called because no more events are allowed to get posted on the service after complete is called and the lingering processors allow for the possibility of memory leak. 
Testing:
Unsure how to test without exposing the processor container which I do not want to do for the design of the class. Passes all unit tests.
> Unresgister after complete

- src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksLogDiffSubCommand.java
This moves a BufferedReader to a try-with-resources statement to fix a bug caught by sonar:
https://sonarcloud.io/project/issues?id=org.openstreetmap.atlas%3Aatlas-checks&issues=AWY4l11cM63is4RDMD9r&open=AWY4l11cM63is4RDMD9r
This will prevent the log diff from breaking if there are bad input files. 
No new unit tests for this. All unit tests pass. 
None
> Log Diff Sonar Bug Fix

- src/main/java/org/openstreetmap/atlas/checks/event/EventService.java
- src/test/java/org/openstreetmap/atlas/checks/event/EventServiceTest.java
Addresses the issue: https://github.com/osmlab/atlas-checks/issues/81  where the processors were getting removed from the collection they were iterating from. This was missed because none of the tests used more than one processors. I duplicated the bug by adding another processor to the common test class method, then fixed by creating anew collection to iterate through upon completion of the EventService. 
No more exception for more than one event service processor. 
Add line to common function used in many test classes that exposes bug.
Fix gets rid of the bug.
> Fix Event Service bug

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
This PR changes the 'L' in 'Lanes' to be lowercase for the `lanesFilter`. This was acceptable before the recent updates the TaggableFilter class in atlas, but no longer gets automatically converted to all lower case. Without this fix, this check is currently flagging every car navigable edge with a lanes tag. 
The check will once again work as intended with default values. 
Nothing changed. 
Ran this on multiple countries before and after. Flag counts dropped back to normal after the fix.
> Update InvalidLanesTagCheck Filter

- src/main/java/org/openstreetmap/atlas/checks/event/CheckFlagEvent.java
- src/test/java/org/openstreetmap/atlas/checks/event/CheckFlagGeoJsonProcessorTestRule.java
This PR is to fix https://github.com/osmlab/atlas-checks/issues/87. A try catch statement is used to ignore bad highway tag values. 
Stop the exception from stopping the program.
A bad highway tag was added to the Area in the test atlas to test for this bug. 
None
> CheckFlagEvent HighwayTag Bug

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTestRule.java
This fixes a bug created by a change of a `LayerTag` method (see https://github.com/osmlab/atlas-checks/issues/77). The check was dependent on the default value the previous method granted. This default has been re-added, though it now takes into account the difference between a bad and non-existent layer tag. This bug should have been caught by the unit tests, but were missed due to a lack of car navigable highway tags. Unit test have been updated to address this.
This PR also includes a change to eliminate redundant flags and a new filter for highway classifications. The new filter was added to eliminate false positives from lower classification roads that can commonly cross. The redundant flags were caused by the check looking at the crossings of a single Edge and then having one of …
> EdgeCrossingEdgeCheck Bug Fix & Enhancements

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BuildingRoadIntersectionTestCaseRule.java
This PR adds following enhancements to the BuildingRoadIntersectionCheck:
1. Adds a configurable `car.navigable` to specify valid highway tags for intersection. The default value of "car.navigable" is set to true. If set to true, the intersecting highways will be checked for tags in the "CAR_NAVIGABLE_HIGHWAYS" enum set of `HighwayTag` class. If set to false, it will be checked for tags in "CORE_WAYS" enum set.
2. Ignores intersections with intersecting highway containing nodes with BarrierTag as these are valid intersections.
3. Ignores intersections with intersecting building containing points with `amenity=fuel` tag. Previously, buildings with `amenity=fuel` was ignored. There are cases where nodes within buildings, which are ingested into Atlas as points, have `amenity=fuel` tag. …
> Building Road Intersection Check Enhancement

- gradle/runchecks.gradle
- src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/test/java/org/openstreetmap/atlas/checks/base/CheckResourceLoaderTest.java
This PR adds the ability to pass in a `-checkFilter` flag into `IntegritySparkJob`. This lets us quickly run one or two checks. For example, now I can run 
```
./gradlew run -Pchecks.local.checkFilter=PoolSizeCheck
```
to quickly get the output for just `PoolSizeCheck`, or 
```
./gradlew run -Pchecks.local.checkFilter=PoolSizeCheck,AddressPointMatchCheck
```
to get the output for multiple checks. 
The code changes are as follows:
* ~addition of an overloaded `loadChecksForCountry(final String country, final Predicate<Class> filter)` function to `CheckResourceLoader`.~
* ~addition of a `loadEnabledChecks(final Predicate<Class> additionalFilter)` function, which loads only the default-enabled checks that also pass `additionalFilter`.~
* addition of a `CheckResourceLoader.checks.whitelist` …
> checkFilter flag for IntegritySparkJob 

- config/configuration.json
- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolyLineCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineTestCaseRule.java
This PR adds a minimum highway type to existing SelfIntersectingPolyLineCheck. The enhancement adds a `minimum.highway.filter` with a default value of `highway=service` to the config so that roads with low priority are not flagged. Valid edges for the check will now be checked for `building tags` or highway tags with equal or higher priority than the config value. 
NA
Added unit tests to test the `minimum.highway.type` configurable.
NA
> Self Intersecting Poly Line Check Enhancement

- .travis/deploy.sh
- build.gradle
- gradle/createStagingId.sh
- gradle/deployment.gradle
- gradle/nexus_description.xml
- gradle/uploadToNexus.sh
This is a hack that allows us to upload artifacts to Sonatype even from GCE.
It is using the maven `uploadArchives` task to upload to a local nexus repo, then uses a script to open a staging repository, get its ID, and specifically uploads each artifact in the repository to the same staging repository in Sonatype. Inspiration comes from [here](https://github.com/h2oai/sparkling-water/blob/73d2e2bd11ce35c6379f6961188fb2af1a7bc04b/build.gradle#L228) and [here](https://github.com/h2oai/sparkling-water/tree/3f8fcf387a2bcc080343a8fafdc81aebc0d99fa1/gradle/publish).
Reference issue: https://github.com/travis-ci/travis-ci/issues/9555
Special thanks to @lucaspcram who helped me with [this bash line](https://github.com/osmlab/atlas-checks/pull/105/files#diff-666bc478d90b3e6e45b5d0fad9e3a94aR7)! …
> [HACK] Upload artifacts to Sonatype from GCE Travis instances

- docs/configuration.md
`CheckResourceLoader` has the ability to override parameters on a country-specific basis, but there is no documentation for this use case. This PR adds documentation in the configuration README so that users have a place to reference without having to dig through source code.
Docs will be a little clearer.
None -- no code changes.
N/A
> Add documentation for country-specific overrides

- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
Expose The filters being used by the check under the hood to filter out objects to flag by area. 
None, getter methods only. No dependencies.
> Expose Check specific and Global Polygon filters

- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
- src/test/java/org/openstreetmap/atlas/checks/base/ChallengeTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/ChallengeSerializationTest.java
Add checkinCommit to support MR java client to pass in another value "", by default it is always "#maproulette".
For more background knowledge, If you manually add a challenge to a project on MR, on the New Challenge page, you are supposed to fill in mandatory fields like name, instructions, and other fields as you like, and there are two radio box indicate that if you want to "Automatically append #maproulette hashtag (highly recommended)" or "Skip hashtag", after debugging, from the http request, we can know that this field is mapped to input parameter checkinCommit with two values as showed below:
So for MR java client, we want to support uses to choose which value they want to use, that is what this PR is trying to do. By default, we still keep this value to "#maproulette" as before. …
> Add checkinCommit to support MR java client to pass in another value

- README.md
- build.gradle
- data/README.md
- docs/standalone.md
- gradle.properties
- gradle/execute.gradle
- src/main/java/org/openstreetmap/atlas/checks/distributed/AtlasDataSource.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
This allows for automatic downloading of a PBF file for a "zero setup" option. Cloning, then `gradle run` should work out of the box.
- Also fixed the bpf to atlas flow that was not way sectioning for some reason.
- Fixed the following NPE:
```
java.lang.NullPointerException
at org.openstreetmap.atlas.checks.validation.tag.MixedCaseNameCheck.flag(MixedCaseNameCheck.java:147)
at org.openstreetmap.atlas.checks.base.BaseCheck.check(BaseCheck.java:126)
at org.openstreetmap.atlas.checks.distributed.RunnableCheck.lambda$run$0(RunnableCheck.java:57)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.openstreetmap.atlas.checks.distributed.RunnableCheck.run(RunnableCheck.java:55)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at …
```
> Updates to the default gradle run command

- gradle/execute.gradle
Update links for `gradle run` command.
Gradle run command should work again
N/A
Tested the command locally.
> Update gradle run links

- gradle/execute.gradle
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteClient.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConfiguration.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Project.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/ProjectConfiguration.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteClientTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/TestMapRouletteConnection.java
Currently, subclasses of MapRouletteCommand are able to connect to MapRoulette through a four-part command-line switch of the form `maproulette=SERVER:PORT:PROJECT_NAME:API_KEY`. However, the endpoint in MapRoulette that creates a project also takes in a `displayName` parameter, which gives the project a more human-friendly name (think `Test Upload` instead of `test_upload`).
This allows users to pass in a project display name separately, like `projectDisplayName=DISPLAY_NAME`.
In order to make this happen, I made changes to the following classes:
- `Project` now has a new `displayName` field, which is automatically serialized by its `toJson` function. There is also now a corresponding constructor and getter for `displayName`. 
- I added a class `ProjectConfiguration`. Semantically, the …
> Small refactor of MapRouletteCommand to add DisplayName parameter

- src/main/java/org/openstreetmap/atlas/checks/flag/CheckFlag.java
- src/main/java/org/openstreetmap/atlas/checks/flag/FlaggedPoint.java
- src/main/java/org/openstreetmap/atlas/checks/flag/FlaggedPolyline.java
- src/main/java/org/openstreetmap/atlas/checks/flag/FlaggedRelation.java
Currently, each flagged object should be able to return a properly formed GeoJSON feature with flag ID information. This got broken with the GeoJSON updates where we are now adding properties find to a geometry object which is not to spec. This constructs the feature for each flagged object in the proper way. 
Flag parsers should work the same way as they did before the breaking update. 
All unit tests the same.
> Fixing GeoJSON creation

- src/main/java/org/openstreetmap/atlas/checks/event/Event.java
- src/main/java/org/openstreetmap/atlas/checks/event/EventService.java
- src/main/java/org/openstreetmap/atlas/checks/event/Processor.java
- src/main/java/org/openstreetmap/atlas/checks/event/ShutdownEvent.java
The `EventService` was moved to [atlas](https://github.com/osmlab/atlas) as a part of https://github.com/osmlab/atlas/pull/324.
None.
NA.
Existing tests successful.
> Deprecate event service

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheckTestRule.java
This PR adds a small enhancement to the existing SinkIslandCheck to exclude edges that are part of pedestrian navigable ways. Many edges that are of type service( `highway = service` and `service = *`) were flagged as floating, but are actually part of pedestrian highway network. The enhancement will filter out edges that are of type `highway = service` and `service =*` and 
1)  are fully enclosed within areas that have amenity = PARKING, PARKING_SPACE, MOTORCYCLE_PARKING,PARKING_ENTRANCE 
Example:
Edge https://www.openstreetmap.org/way/472780972 is within a parking lot
2) are connected to any of the pedestrian navigable ways defined in the Highway class. Example: https://www.openstreetmap.org/way/333824047 way is connected to a pedestrian way
A drop in number of previously flagged items …
> Sink Island Check Enhancement to Filter Pedestrian Navigable Highways

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheck.java
This is a hot fix to fix a bug with the latest enhancement to the SinkIslandCheck. The enhancement added a condition to the `validEdge()` which resulted in some FP which were not caught in the initial analysis. The fix is to extract the condition that checks for service edges that are fully enclosed in amenity areas, from the `validEdge` method to `validCheckForObject` method. Some of the edges that were connected to service roads that were within amenity areas were incorrectly flagged because the out edges (service roads within amenity) of these edges were invalid and so the edges were flagged as floating.
Example:
Enhancement would have added some FP flags which are removed with this fix.
Ran a pre and post enhancement flag diff to validate the flags dropped.
All unit tests passing and …
> Hot Fix for Sink Island Check Enhancement Bug 

- docs/standalone.md
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConfiguration.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConfigurationTest.java
This fixes a bug with the MapRouletteConfiguration and MapRouletteConnection. Previously these assumed that all URIs used, but did not include, the `http` scheme (e.g. maproulette.server.mine:42 vs http://maproulette.server.mine:42). This updates MapRouletteConfiguration and its `parse` method to look for and store schemes, or continue to use `http` as a default. MapRouletteConnection has been updated to look for the set scheme and use that in building a URI.
Additionally, MapRouletteConfiguration now throws a CoreException when it fails to parse a configuration string, instead of logging a debug message and trowing a NPE. This is preferable, as debug messages are not written to stdout by default, and this is important information for the user. 
This is generally non-breaking, due to the …
> Map Roulette Configuration Full URL Parsing Bug

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTestRule.java
This adds two filter arguments to the MapRouletteUploadCommand. One is a list of ISO3 country codes, the other is a list of names of atlas checks. If either or both filters are provided, only flags that have values that are in the filters will be uploaded. 
No impact, just optional arguments.
A unit test for each filter was added. Test rules and log file generation were altered to accommodate this. 
None
> MapRouletteUploadCommand Country and Check Filters

- build.gradle
Resolve dependency issues introduced by the update of the spark version in atlas-generator.
Should enable running of the integrity checks spark job again. Issue introduced https://github.com/osmlab/atlas-checks/issues/164
No unit tests because it is a runtime dependency issue. 
-ran the job before and after to confirm that it was broken as observed and fixed as intended.
Builds and runs normally.
> Decency resolve for new Spark

- src/main/java/org/openstreetmap/atlas/checks/commands/FlagStatisticsSubCommand.java
There is a bug in the Flag Statistics command caused by the parallelStream file reader writing to a single hash map. This was causing flag counts to be lower than expected. This fixes the bug by mapping each file to its own hash map, and using a collector to combine all the maps. 
NA
No change.
Tested against a data set generated using a non-parallel stream. Results for the old parallel single map system differed from the non-parallel. The new collector system created the same results as the non-parallel run.
> Flag Statistics Command Parallel Bug Fix

- src/main/java/org/openstreetmap/atlas/checks/commands/FlagStatisticsSubCommand.java
This changes the default output types for the FlagStatisticsSubCommand to be all output types. 
Anything that used the default will see an increase in output files. 
No new unit tests.
Tested with and without the output-types argument. The results were as expected.
> Flag Statistics: All Outputs By Default

- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/base/TaskIdentifier.java
- src/main/java/org/openstreetmap/atlas/checks/flag/CheckFlag.java
Currently, CheckFlag constructors that accept a `Set` require the set to be exactly `Set<AtlasObject>`. This creates an awkward step if we, for example, want to flag the results of a walker (which returns `Set<Edge>`). 
According to [PECS](https://stackoverflow.com/questions/2723397/what-is-pecs-producer-extends-consumer-super), we should use the exact match (`<AtlasObject>`) if we are both reading from and adding to the data structure. However, the constructors only read from the set. So, we can safely read any `<? extends AtlasObject>`.
I think this is a pretty clear win as far as improved flexibility goes. 
Increased flexibility in calling `createFlag` and similar methods. There should be no function calls that were valid before but are no longer valid.
Classes in other libraries that …
> CheckFlag accepts ? extends AtlasObject

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
With the addition of the CompleRoundabout class to Atlas, much of the logic in MalformedRoundaboutCheck is redundant. This removes the redundant logic and replaces it with calls to ComplexRoundabout.
There should not be any downstream impact. 
Added one unit test for the left driving countries configurable.
Tested the check on 5 countries. The flags were the same before and after the changes.
> MalformedRoundaboutCheck Use ComplexRoundabout

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
This updates the `MapRouletteUploadCommand` to pick up the Challenge `name` from the default configuration object if it exists.
```json
"AddressPointMatchCheck": {
"challenge": {
"name": "Missing Address Points",
"description": "Tasks contain nodes which either have no street name or incorrect street names",
"instruction": "Open your favorite editor and edit the node street names"
}
}
```
Before creating new challenges, the MR client checks if the challenge exists via the `/api/v2/project/{id}/challenge/{challenge_name_string}`. To allow for challenges with special characters/spaces etc., I've encoded the challenge name string.
No downstream impact. Command is optional
Existing Challenge Deserialization unit tests handle this case. Using the default configuration, I added names to both …
> [MapRouletteUploadCommand] Pick up Challenge name from configuration

- config/configuration.json
Unquote number in configuration.json which was causing build to fail
NA
NA
NA
> Unquote number in configuration.json

- src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
- src/test/java/org/openstreetmap/atlas/checks/base/CheckResourceLoaderTest.java
- src/test/java/org/openstreetmap/atlas/checks/base/checks/ContextAwareTestCheck.java
Currently, CheckResourceLoader.loadChecks() assumes that the only constructors present on a check are `Check(Configuration config)` and/or `Check()`. However, it would be nice to potentially pass in some extra context through subclasses. For example, I can imagine a `ContextAwareCheck` that subclasses `Check` and stores some extra data passed in at initialization time. 
This PR introduces a new method on `CheckResourceLoader` to allow for this called `loadChecksUsingConstructors`. In the following example, we define the following priority over constructor calls with `constructorArgumentTypes`:
- `new Check(Configuration config, int value)`
- `new Check(Configuration config)`
- `new Check()`
Checks get initialized with the first argument set for which they have a constructor, so this …
> Expose new loadChecksUsingConstructors method

- src/main/java/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommand.java
- src/main/resources/org/openstreetmap/atlas/checks/database/schema.sql
I've updated the `flag_id` column in the `feature` table to reference the `flag.id` column (instead of `flag.flag_id`) in the `flag` table. 
This issue was exposed when creating a view (as a QGIS layer) that left joins the flag & feature table together on the `flag_id` (non unique check flag identifier) column:
```SQL
CREATE MATERIALIZED VIEW IF NOT EXISTS vw_check_flags AS
SELECT feature.id, feature.flag_id, geom, osm_id, atlas_id, iso_country_code, item_type, tags, flag.check_name, flag.instructions
FROM flag, feature
WHERE feature.flag_id = flag.id
``` 
I've also updated the software version column name to be more generic.
The value and data type in the feature table has changed from text to integer. Also, the software version column name has changed. This should not be a problem given …
> [FlagDatabase] Set feature flag_id as foreign key

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/lines/GeneralizedCoastlineCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/GeneralizedCoastlineCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/GeneralizedCoastlineCheckTestRule.java
Added a `source=PGS` tag filter to the GeneralizedCoastlineCheck.  Features with `source=PGS` tag are often generalized so this filter was added to filter for those features specifically. 
This will filter out generalized coastline features that do not have the tag `source=PGS` by default so the number of features found by this check previously will change. The filter for `source=PGS` is configurable since it was added to the configuration.json.
Updated the existing unit tests to have test atlases with `source=PGS`. Additional tests were added for testing `source=PGS` tag filtering.
Unit tests pass
> [GeneralizedCoastlineCheck] Added source=PGS tag filter

- src/main/java/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommand.java
- src/main/resources/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommandExamplesSection.txt
- src/main/resources/org/openstreetmap/atlas/checks/database/schema.sql
- src/test/java/org/openstreetmap/atlas/checks/database/FlagDatabaseSubCommandTest.java
This adds two new arguments to the FlagDatabaseSubCommand: `run_uri` and `software_version`. Both are optional arguments used to pass meta data about the generation of the flags that are being uploaded. 
This also changes the type of the software_version column to remove an arbitrary character limit. 
None, the arguments are optional. 
Updated two unit tests so that the arguments can be retrieved from the `executeFlagStatement` method. 
Tested uploading data to a local database using the new arguments. 
Both before the update and when not passing the arguments the flag table looked like this:
When the arguments were provided (tested using long and short form argument names) the flag table looked like this:
> FlagDatabaseSubCommand: Add Meta Data Arguments

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
We've been uploading MapRoulette challenges using the ISO country identifier as part of the challenge name. We should be converting ISO codes to full country names in challenge names for MapRoulette uploads, so challenge locations are more immediately obvious for editors. For example, ARG - SinkIslandCheck should become Argentina - SinkIslandCheck. This PR changes the country identifier from the ISO code to the full country name.
Challenge naming standard is changed to include full country name, not ISO code.
Same unit tests
Tests pass, and a sample upload excerpt shows the following:
> [MapRouletteUploadCommand] Use full country name for MR uploads

- src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
MixedCaseNameCheck had 2 nondeterminism issues in which 1.) master/reverse edges were being flagged unpredictably and 2.) Atlas objects of different types but with the same OSM identifier (e.g. an Edge and Area both from the same OSM Way) were being flagged unpredictably. The 2nd issue was due to the check's flags being unique purely by the OSM ids of atlas objects.
This PR fixes these 2 issues by only flagging master edges if the AtlasObject is an edge, and having flags record the unique identifier of atlas objects rather than the OSM identifier. The unique id is the atlas object type and the OSM id. e.g. E389377982
Flag count changes for MixedCaseNameCheck should be anticipated. We should see more flags, if anything.
Same unit tests. The unit test Verifier class analyzes CheckFlags, not …
> [MixedCaseNameCheck] Fix AtlasObject nondeterminism issue

- src/main/java/org/openstreetmap/atlas/checks/validation/areas/ShadowDetectionCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/ShadowDetectionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/ShadowDetectionCheckTestRule.java
ShadowDetectionCheck had an issue parsing tags in neighborsHeightContains(). The program can guarantee that one of MinHeightTag and BuildingMinLevelTag exists (via validCheckForObject). It will fall back on the latter if either the former doesn't exist or has an invalid value. In the first case, this is OK since a BuildingMinLevelTag is guaranteed to exist. But in the second case, we can't guarantee that BuildingMinLevelTag exists too. So an NPE is thrown in this case when it tries to parse the empty BuildingMinLevelTag tag.
The PR makes a simple change to address this issue, where if BuildingMinLevelTag doesn't exist then a default value is used.
With the elimination of failures, we can expect to see more flags in some countries.
Added a unit test for the use case causing the failure. …
> [ShadowDetectionCheck]Tag parsing bug

- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BigNodeBadDataCheck.java
BigNodeBadDataCheck can often load Edge networks consisting of tens of Edges. In these cases it takes a long time for the AllPathsRouter to execute on the network. In some rare cases the check will even time out before completing due to this.
The AllPathsRouter is used to calculate the number of paths through a big node. If this number is too high then that is one of the conditions for the big node to be flagged.
To fix this issue the check has been altered to only run the AllPathsRouter (through `BigNode.allPaths()`) if no other conditions for flagging are met. 
BigNodeBadDataCheck should run much more quickly. There may be an increase in flags in areas where the check was previously timing out. 
In most cases the flag instructions will no longer include information on the path count or …
> BigNodeBadDataCheck Run Time Bug

- src/main/java/org/openstreetmap/atlas/checks/configuration/ConfigurationResolver.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheckTestRule.java
This PR is a bug fix for existing connectivity check. The code checks for synthetic boundary nodes and if the nodes are not one of them it creates flags. Other validations are left as is.
Changes made to Atlas-checks.
Added one unit test for validating flags with added synthetic node.
Using some Atlas files, verified that the starting node and near by nodes are checking the synthetic boundary condition which is added and filter on it. Also, will take analyst help to analyze the flags correctly.
> Connectivity check bug fix.

- README.md
- build.gradle
- dependencies.gradle
This PR sets Atlas Checks to target JDK 11. Updating to 11 required a few changes to dependencies:
- Atlas generator 5.0.0 (brings in spark 2.4.4)
- Atlas 6.0.1 (requires us to override its version of jackson (2.9.8) to the spark 2.4.4 supported 2.9.7 )
Atlas checks build will no longer support JDK 8
Local build
Build passed
> JDK 11 support

- gradle.properties
Description:
Update gradle.properties version to 6.0.0
built locally
Test Results:
successful
> Bumping gradle.properties to 6.0.0

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/InconsistentRoadClassificationCheck.java
InconsistentRoadClassificationCheck flags Edges in a nondeterministic manor. It should only flag master Edges and use the OsmWayWalker. Fixed this issue in current PR.
Changes made to Atlas checks.
No additional tests are included.
Tested by running the check on atlas files and the changes are working as expected.
>  Inconsistent-road-classification bug fix

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SnakeRoadCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SnakeRoadNetworkWalk.java
This is a bug fix for the existing Snake Road Check.
Existing code is meeting all the requirements except for instead of doing heading difference for connected edges the current edge was doing heading difference with all the edges on the highway. This issue is fixed with new code changes.
Criteria to identify Snake Road is as follows:
- At some point, two consecutive edges making up the Snake road must have a heading difference of at least 60 degrees.
- The snake road must have at least 3 edges
- At least one edge making up the snake road should have a valence greater than 4
- To be considered a snake road, you should either have no road name or have any connected ways that share the 
same name that you do. This is done to prevent flagging strange portions of highways that may exhibit the …
> Snake road check bug

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoadLinkCheck.java
RoadLinkCheck flags Edges in a nondeterministic manor. It should only flag master Edges and use the OsmWayWalker. Current PR will address these issues.
Changes will be made in Atlas Checks.
Current unit tests are fixed.
Ran the check on approximately 60MB data and its working as expected.
> Road link check

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
This updates the MapRoulette createChallenge function to use [URIUtil.encodeQuery](https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/util/URIUtil.html#encodeQuery(java.lang.String)) to encode Challenges names in the /api/v2/project/{project_id}/challenge/{challange_name_string}.
This will fix an issue where the MapRouletteUpload command would return a 500 when uploading tasks to an existing challenge.
```
16:54:37.982 [main] DEBUG o.o.a.c.m.MapRouletteConnection - 500 - 
{
"status": "KO",
"message": "Challenge with name USA - SelfIntersectingPolylineCheck already exists in the database"
}
```
`URLEncoder.encode` replaces space characters with `+` instead of `%20`, which is not properly decoded by the MapRoulette API. 
This will allow us to use …
> [MapRouletteUploadCommand] Encode challenge names with URIUtil

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/URIException
at org.openstreetmap.atlas.checks.maproulette.MapRouletteClient.<init>(MapRouletteClient.java:83)
This is happening because the URIUtil class which is used in Atlas checks is of older Apache Commons version i.e., 2.6. OSM Integrity is using Apache Commons version 4.1.
The newer version doesn't have the class URIUtil. So, I replaced the URIUtil with URLEncoder from JDK11. It takes care of encoding the string using URLEncoder. But, spaces are encoded to "+" instead of "%20" as mentioned in the below document. It is taken care of using replace method from String class.
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLEncoder.html
Changes made to Atlas checks
No changes made to existing tests. …
> Maproulette-upload-dag, fix for url encoding issues.

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheckTestRule.java
SinkIslandCheck has a list of tag key/values that are used to help define navigable Edges for the check. This updates that list to include the values `designated` and `permissive` for the `motorcar`, `motor_vehicle`, and `vehicle` tags. 
This also makes a small change to the checks graph search to make it more deterministic. Instead of using an unsorted set to collect connected Edges, a sorted list is now used. This ensures candidates are added to the queue in the same order on every run. 
Small drops in flag counts should be expected.
A unit test was added to test the new values
Checked the difference in flags for 7 countries. Out of 84 flags, all were found to now be correctly handled in terms of navigability.
> SinkIslandCheck Navigability Enhancement

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTestRule.java
This added enhancement will allow for the option to check if floating edges are connected to construction roads or not. By default, edges are considered floating if they are connected to construction roads and not connected to any other edges.
No impact if configuration is left as default. If the configuration is changed to true, there will be less edges flagged.
> Add construction configuration

- docs/shardedchecks.md
- src/main/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJob.java
In earlier designs of the ShardedIntegrityChecksSparkJob it was necessary to gather all UniqueCheckFlagContainers together into a single RDD. This was required to perform a sorting and reduction process to countrify the results. Now that the tasks are parallelized in a countrified manor this is no longer necessary, and causes spark to perform a very large, unnecessary shuffle operation.  
This removes the RDD union in favor of running the flag reduction and file writing operations as part of each countrified stream. This should increase performance for the job on clusters by reducing the amount of communication necessary between executors. 
With the removal of the union it is no longer necessary to persist any RDDs. As such, the spark storage option is no longer needed, and has been …
> ShardedIntegrityChecksSparkJob RDD Union Removal

- src/main/java/org/openstreetmap/atlas/checks/flag/FlaggedRelation.java
For all FlaggedObjects, except FlaggedRelation, the "osmIdentifer" and "identifier" fields in the feature properties are string. In case of FlaggedRelation, these fields are populated as integers. This PR updates the "asGeoJsonFeature" method in FlaggedRelation to populate the  "osmIdentifer" and "identifier" fields as string instead of as integers.
List potential impact to downstream libraries here (ex. atlas-checks, atlas-generator)
The "identifier" and "osmIdentifier" keys in the properties of geojson features for FlaggedRelation will be string just like in other FlaggedObjects.
Locally ran the updates on checks that flag relation and verified the geojson and log files
Before updates:
After updates:
> Update FlaggedRelation to Output Atlas Identifier and OSM Identifier as String

- README.md
- docs/dev.md
- docs/standalone.md
- gradle.properties
- gradle/execute.gradle
This changes the default behavior of the `gradle run` command to use the ShardedIntegrityChecksSparkJob instead of the IntegrityCheckSparkJob. 
The `mainclass` property has been replaced with a `sharded`. This new property acts as a switch to designate which spark job to use. If it is true (default) the sharded job is used, else the regular checks job is used. 
As part of this change the example run had to be altered to use Atlas files instead of a PBF. By default `gradle run` will now download example BLZ atlases and a sharding tree, and run sharded checks on that data. 
The documentation has been updated to reflect these changes. 
If any downstream projects rely on the `gradle run` command they will see a change in the spark job used. 
None
Tested the `gradle run` command on the example …
> Update Gradle Run to Use Sharded Checks By Default

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTestRule.java
The MapRoulette upload command is able to upload a subset of flags in the input directory according to which countries are passed in to the `-countries` flag. However, there were issues when a given Check was found in more than one country passed in to the `-countries` flag. For example, if LineCrossingWaterBodyCheck was found in PER and PRY, and those two countries had their flags uploaded using the upload command. This caused the flags from both countries to be grouped under a single Challenge (determined by encounter order while parsing the log file), e.g. everything goes under "Peru - LineCrossingWaterBodyCheck".
The fix in this PR makes sure that if a Check name is found in more than one country, separate challenges are created and flags stored accordingly. In the example above, this …
> [MapRouletteUploadCommand] Fix countrified challenge names

- gradle.properties
The next version bump from atlas-checks 6.0.5 to 6.0.6.
> Atlas-Checks version bump from 6.0.5 to 6.0.6 in gradle.properties

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheckTest.java
InvalidMultiPolygonRelationCheck was recently enhanced to include tests for overlapping polygon members. However these test are computationally heavy. In the case of extremely large multipolygon relations this can take an excessive amount of time. To help manage this two new configurable are added. These configurable are used to limit the size of relations that are checked for overlapping polygons in their geometry. If the number of shape points in a multipolygon relation's geometry falls outside the limits of the configurables then the overlap test will be skipped. All other tests in the check will still be performed on all multipolygon relations. 
**New Configurables**:
`"overlap.points.minimum"`: minimum number of shape points to be eligible for overlap tests (default 0) …
> InvalidMultiPolygonRelationCheck Overlap Test Limits

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
Small change to the MapRouletteUploadCommand file out empty lines in files, which would cause an NPE when trying to deserialize them into Tasks:
```bash
java.lang.NullPointerException: null
at org.openstreetmap.atlas.checks.maproulette.MapRouletteUploadCommand.lambda$execute$5(MapRouletteUploadCommand.java:127) ~[classes/:na]
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
at org.openstreetmap.atlas.checks.maproulette.MapRouletteUploadCommand.lambda$execute$6(MapRouletteUploadCommand.java:121) ~[classes/:na]
at …
```
> [MapRouletteUploadCommand] Filter empty lines

- gradle.properties
Bumping the atlas-checks version in order to do the next release for 6.0.8
> atlas-checks version bump for next release; 6.0.8

- src/main/java/org/openstreetmap/atlas/checks/flag/serializer/CheckFlagDeserializer.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/ChallengeStatus.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/serializer/TaskDeserializer.java
This brings in the following changes to the command:
* Replaces the Task name with the _new_ CheckFlag identifiers array.
* Sets the challenge to disabled by default
* Adds a `checkinCommentPrefix` switch to create a  check-in comment prefix `[prefix]: [challenge name]`
* Sets the challenge status to ready
List potential impact to downstream libraries here (ex. atlas-checks, atlas-generator)
Uploaded challenges to staging maproulette
> [MapRouletteUploadCommand] Various changes to maproulette upload command

- gradle.properties
Bumping the atlas-checks version in order to do the next release for 6.0.9.
> Updating the version for the next release. 6.0.9

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
Adds a new `checkinComment` switch to the MapRouletteUploadCommand. This allows us to either:
1. Set the `checkinComment` value
2. Set the prefix for the [checkinComment](url) value
The `checkinComment value overwrites the `checkInCommentPrefix` value.
Why do we need both?
This switch is available for users that do not want the check name and iso country code in their check-in comment.
More options for MapRouletteUploadCommand
Uploaded some tests to the public staging environment
Challenge values look good 👍
> [MapRouletteUploadCommand] Overwrite checkInCommentPrefix with additional switch

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheckTestRule.java
This update InvalidMultiPolygonRelationCheck to flag features that have the new SyntheticInvalidGeometryTag. This tag is used by Atlas to mark features that were found to have invalid geometries, during the country slicing process. 
This PR bumps the atlas version to 6.2.1, to access the new tag.
Will add a few flags.
Added a unit test for a feature with the tag. 
Tested on several countries and sampled the added flags. All the sampled features had the new tag and invalid geometries in OSM.
> InvalidMultiPolygonRelationCheck Flag Features Marked By Atlas

- config/configuration.json
- docs/available_checks.md
- docs/checks/approximateWayCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/ApproximateWayCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/ApproximateWayCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/ApproximateWayCheckTestRule.java
This checks for ways that were done crudely, there is a discrepancy between the drawing and the real way especially in the curve. Roads are expected to be smooth and consistent, large changes in directions are suspect of poor drawing. Fixing these visually improves the map.
* Is an Edge
* Has a highway tag that is car navigable
* Edge has more than one segment
Case 1: False Positive (US)
* This gets flagged due to the sharp angle in the edge, this edge is the same road throughout and matches the imagery
* https://www.openstreetmap.org/way/608161473
Case 2: True Positive (US)
* Curves are not smooth, poorly drawn
* https://www.openstreetmap.org/way/40195903
| Country | Total Ways Checked | False Positives | FP % |
|----------|:---------------------:|:---------------:|:-------:|
|   AUS …
> ApproximateWayCheck

- Dockerfile
- docs/dev.md
- docs/docker.md
This adds a simple Dockerfile & documentation for local development use. By default, the `gradlew` command is exposed by the Docker container.
Steps for use:
1. Create image
```bash
docker build --rm --tag [image name] .
```
2. Create container from image and execute command
```bash
docker run [image name] [gradle command]
```
Example
```bash
docker build --rm --tag checks .
docker run checks run -Pchecks.local.checkFilter=SpikyBuildingCheck \
-Pchecks.local.countries=AIA
```
Fixes #289 #293 
No downstream impact
Created and image and container. Was able to execute both gradlew build and run commands.
Tests pass!
> Add simple Dockerfile sandbox & docs

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTagsCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTagsCheckTest.java
This PR fixes a bug in InvalidTagsCheck, introduced in PR #[296](https://github.com/osmlab/atlas-checks/pull/296). The config values for Taggable filter passed through the config.json was not initialized properly and was always set to null and so the check did not produce any flags for filters passed through the config.
By this update, the config values in the check will be properly initialized to values passed through config.json.
Updated existing unit tests
Tested locally and verified that the outputs are generated properly for the filters passed through the config.
> Fix issue with InvalidTagsCheck configurables

- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/AtGradeSignPostCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/AtGradeSignPostCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/AtGradeSignPostCheckTestRule.java
This PR adds following updates to the existing AtGradeSignPostCheck:
1) In case of At-Grade junctions with turn lanes between connected edges, the AtGradeSignPostCheck flags the Link road instead of the connected edges of the at-grade junction. This update is made considering the fact that the destination information should go to these link roads as they are the most logical routes at such junctions.
Example:
In the above image, the inEdge and outEdge of the at-grade junctions(https://www.openstreetmap.org/node/5992479635) were flagged previously for missing destination_sign relation/ destination_sign tag. The link road https://www.openstreetmap.org/way/611793210 is the most logical route from the flagged inEdge to the flagged outEdge. With this enhancement, the link road will be flagged …
> Updates to AtGradeSignPostCheck

- scripts/check-log-splitter/README.md
- scripts/check-log-splitter/log_splitter.py
Atlas Checks line delimited geojson output (flag output) combines all check outputs into timestamped named .log files. This makes it difficult to parse individual check results. This script converts Atlas Checks line delimited json output files into check separated .log files.
None. This script aids in analysis process.
NA
Verified that the script outputs .log files separated by check names by local testing. See README.md for usage and output formats.
> Add a Script to Split Atlas Checks Log Files By Check Name

- config/configuration.json
- docs/available_checks.md
- docs/checks/bridgeDetailedInfoCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/BridgeDetailedInfoCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/BridgeDetailedInfoCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/BridgeDetailedInfoCheckTestRule.java
Port of Osmose check #7012. Flags long bridges without detailed info (bridge type/structure).
Issue https://github.com/osmlab/atlas-checks/issues/341
None.
Unit tests created for two positive scenarios (railway and major-highway bridges that meet all preconditions) and several negative scenarios (when some of the preconditions or check criteria are not met). Tests use local mini-atlases with artificial data.
| NZL | 24 | 24 | 100% | 24 | 0 | 0% |
| ARG | 62 | 20 | 33% | 20 | 0 | 0% |
| BOL | 3 | 3 | 100% | 3 | 0 | 0% |
| COL | 17 | 17 | 100% | 17 | 0 | 0% |
| DMA | 0 | 0 | 100% | 0 | 0 | 0% |
| CYM | 0 | 0 | 100% | 0 | 0 | 0% |
| TUR | …
> New check: Missing bridge structure (#341)

- config/configuration.json
- docs/available_checks.md
- docs/checks/waterAreaCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/WaterAreaCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/WaterAreaCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/WaterAreaCheckTestRule.java
This should fix #345.
This pull request should depend upon #332 .
There should be no down-stream impact at this time. This may change (intersection logic).
Unit tests are largely for false negatives, but there are some false positive checks as well.
Describe other (non-unit) test results here. In case of a new check or enhancements to existing 
checks, please add details on how many countries the check was tested on,
total flag counts, FP rate etc. (see below example).
| AIA | 0 | 0 | N/A | 0 | 0 | N/A |
| CYM | 0 | 0 | N/A | 0 | 0 | N/A |
| DMA | 0 | 0 | N/A| 0 | 0 | N/A |
| NZL[1] | 594 | 61 | 10.2% | 60 | 1 | 1.6% |
| SMR[2] | 2 | 2 …
> Water Area checks

- config/configuration.json
- docs/available_checks.md
- docs/checks/waterWayChecks.md
- docs/utilities/elevationUtilities.md
- scripts/elevationData/requirements.txt
- scripts/elevationData/srtm-hgt.py
- src/main/java/org/openstreetmap/atlas/checks/utility/CommonTagFilters.java
- src/main/java/org/openstreetmap/atlas/checks/utility/CompressionUtilities.java
- src/main/java/org/openstreetmap/atlas/checks/utility/ElevationUtilities.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/OceanBleedingCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheck.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CompressionUtilitiesTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/ElevationUtilitiesTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheckTestRule.java
This does basic waterway checks (closed waterway, waterway does not end in sink, crossing waterway).
See #331.
There are also two new utility classes, `ElevationUtilities` and `CompressionUtilities`. The `ElevationUtilities` reads HGT files (for example, those provided by the SRTM NASA mission), and when given a point, returns the elevation for the appropriate location (only as accurate as the source data -- it _should_ be able to take arbitrarily accurate HGT files). `ElevationUtilities` reads from `elevation` directory in the directory that the check run is started from. This can be customized. `CompressionUtilities` is used to decompress file streams, so that if a file is in a `tar.gz`, `zip`, `gz`, or isn't compressed at all, the user can be relatively certain that the stream is now …
> Basic waterway checks

- Dockerfile
This fixes an issue with the Docker file that would throw the following error when attempting to execute specific gradle commands:
`"run" is not a Task found in root project 'gradle'`
Looking at the image, it turns out the working directory was set to /home/gradle:
No downstream impact. 
Ran the following commands:
```
docker run checks run
docker run checks clean build
```
Build worked as expected
> [Dockerfile] Add working directory

- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityChecksCommandArguments.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJob.java
This is to fix a bug with `IntegrityChecksCommandArguments.countryShardMapFromShardFiles()`. This method reads the input atlas files to assign shards to countries. For each country it was recursively reading all files in the input path. This fixes it so for each country it only reads the country's folder, and it only reads the file name instead of opening the file. 
This should increase the pre-spark speed of the job.
None
Tested locally and observed that only the file names for a single country were read in for each country.
Tested with remote files and saw a 73% decrease in overall runtime.
> countryShardMapFromShardFiles Reads too Much

- src/main/java/org/openstreetmap/atlas/checks/event/CheckFlagEvent.java
- src/main/java/org/openstreetmap/atlas/checks/flag/CheckFlag.java
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheck.java
- src/test/java/org/openstreetmap/atlas/checks/event/CheckFlagEventTest.java
- src/test/java/org/openstreetmap/atlas/checks/event/CheckFlagEventTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/flag/CheckFlagTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheckTest.java
This is an expansion of the CheckFlag data structure to allow checks to add suggested fixes for data errors.
These suggested fixes can be added in the form of FeatureChanges. Ideally the FeatureChanges are created by altering CompleteEntity copies of AtlasEntitys that in the flaggedObjects of the CheckFlag. The FeatureChanges should also include a before view of the feature by providing an atlas context when creating it. The before view is necessary to calculate the changes made to the feature. 
2 new methods are added to CheckFlag for adding fix suggestions: `addFixSuggestion(FeatureChange)` and `addFixSuggestions(Collection<FeatureChange>)`. Both return the CheckFlag to allow for chained calls. 
A getter is also added for the fix suggestions: `public Set<FeatureChange> …
> CheckFlag Fix Suggestions

- gradle.properties
Updating the version of atlas-checks to 6.1.2-SNAPSHOT for this release.
> Updating the version atlas-checks

- gradle.properties
This is the version bump after the current release. Prep for next release.
> Bump version to 6.1.3 after release

- config/configuration.json
- docs/available_checks.md
- docs/checks/constructionCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/ConstructionCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/ConstructionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/ConstructionCheckTestRule.java
This check checks if a features construction tag has not been updated for more than 2 years or the opening date has been exceeded.
| Country | Total Objects Checked | False Positives | FP % |
|----------|:-------------------------:|:---------------:|:-------:|
|   AUS     |              120                  |           0           |    0%  |
|  TUR      |              120                  |           0           |    0%  | 
|  NZL      |              137                  |           0           |    0%  |
|  DMA    |              1                      |           0           |    0%  |
Yes, DMA did only have one flagged object.
Also tested on CMY but had no results.
Resolves #353
> Construction check

- config/configuration.json
- docs/available_checks.md
- docs/checks/tunnelBridgeHeightLimitCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/TunnelBridgeHeightLimitCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/TunnelBridgeHeightLimitCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/TunnelBridgeHeightLimitCheckTestRule.java
Port of Osmose check #7130. Flags tunnels, covered roads and roads crossing bridges, for which maxheight or maxheight:physical tag is not provided.
Issue #343
None.
Unit tests created for each of the three positive scenarios (a tunnel, a covered road and a road which passes under a bridge) and several negative scenarios (when some of the preconditions or check criteria are not met). Tests use local mini-atlases with artificial data.
| NZL | 307 | 77 | 25% | 77 | 0 | 0% |
| DNK | 568 | 127 | 22% | 127 | 0 | 0% |
| ARG | 734 | 110 | 15% | 110 | 0 | 0% |
| LUX | 199 | 50 | 25% | 50 | 0 | 0% |
| VNM | 772 | 80 | 10% | 80 | 0 | 0% |
> New check: TunnelBridgeHeightLimitCheck (#343)

- dependencies.gradle
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheckTest.java
Bumping atlas version to 6.3.2. This required updating two unit tests for InvalidMultiPolygonRelationCheck, to account for the new JTS multipolygon generator providing better errors. 
Should only affect this repo.
Updated the lists of expected open points for two InvalidMultiPolygonRelationCheck unit tests. The new JTS multipolygon generator provides extra points when throwing an OpenPolygonException.  
No non-unit test tests.
> Atlas Version Bump

- src/main/resources/org/openstreetmap/atlas/checks/validation/tag/invalid-tags-check-regex-filter.json
This adds a new regex filter to InvalidTagCheck. Osmose 3040.
No impact.
No new unit tests.
|  NZL   |    4201         |    20      |     0.47%       |   20 |   0 | 0%   |
Resolves: #349
> Added new regex filter to InvalidTagCheck, Osmose 3040

- scripts/cloud-check-control/README.md
- scripts/cloud-check-control/cloudAtlasCheckControl.py
Add a script that automates the execution of Atlas Checks on an EC2 Instance. Please see README.md for details
No impact to Atlas Check code.
No Unit tests performed.
This change was tested with our AWS setup that includes a template for Atlas Checks that we use to start EC2 instances. To complete this script I plan on adding a "Prep" command that will create an EC2 instance from scratch and install necessary support components to make this script work from a native EC2 instance. Until that is completed this script assumes that the user has a launch template with the correct environment to execute the Atlas Checks spark job.
> Add script to automate Atlas Checks Spark job on EC2

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutMissingTagCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutMissingTagCheckTest.java
Convert RoundaboutMissingTag Check to AutoFix https://github.com/osmlab/atlas-checks/issues/416
This Check is no longer available for regular editing after conversion to AutoFix
Verify that flag include the AutoFix suggestion
Passed
> Autofix RoundaboutMissingTag

- dependencies.gradle
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheckTest.java
Bumps the atlas version to 6.3.3. 
This required reverting the changes to InvalidMultiPolygonRelationCheckTest made in https://github.com/osmlab/atlas-checks/pull/400, due to https://github.com/osmlab/atlas/pull/705.
This fixes https://github.com/osmlab/atlas-checks/issues/427
Just the standard atlas version bump. 
Had to update the 2 InvalidMultiPolygonRelationCheck unit tests that were changed recently due to issues discovered that cause nondeterminism. 
None
> Bump Atlas Version

- src/main/java/org/openstreetmap/atlas/checks/validation/areas/WaterbodyAndIslandSizeCheck.java
The main thing this PR does is make the definition of waterbodies configurable. It also strives for more uniform flagging when encountering Relation members and Areas so that resulting flags are not nondeterministic. Other changes are just sonar fixes; e.g. collapsing nested conditionals. Also, Polygon's `surfaceOnSphere()` is used now instead of `surface()` to estimate square meterage of features of interest, as there are orders of magnitude differences between the two methods. When setting limits to feature sizes for flagging, the accuracy of these estimates down to the 10th or 100th of a sq. meter become important.
WaterbodyAndIslandSizeCheck should produce different flags for waterbodies based on the new waterbody definition being passed in. We may also get more flags for other …
> [WaterbodyAndIslandSizeCheck] waterbody configurable

- docs/checks/constructionCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/ConstructionCheck.java
This alters the ConstructionCheck to use the Atlas generation date instead of the current date for comparing against feature dates. 
Using the current date was causing false positive cases because of the time differential between when the data was cut and when the check was being run. It also made it so that running the check with the same input parameters on different days would result in different flags. This causes issues for software validation. 
If the atlas generation date is not available the check defaults back to using the current date. 
Should make the flags produced by ConstrucitonCheck more accurate and stable.
none
Ran the check on a year old atlas and compared the differences in results for pre and post enhancement. The only differences were flags dropped post enhancement, …
> ConstructionCheck Use Atlas Generation Date

- src/main/java/org/openstreetmap/atlas/checks/utility/CommonMethods.java
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTestRule.java
Please refer: https://github.com/osmlab/atlas-checks/issues/442
1) Calculate OSM Relation Member size **excluding** Atlas `Reversed` and `Sectioned` edges
2) Creating CommonMethods Utility Class for using same logic in different Checks 
OneMemberRelationCheck - to flag more relations
InvalidMultiPolygonRelation - to flag less relations
Simulate relation to cover all cases:
1) Relation with edges and nodes
2) OneMemberRelation with reverse edge
3) OneMemberRelation with sectioned edges 
OneMemberRelationCheck - passed
InvalidMultiPolygonRelation - passed
CommonMethods - passed
> OSM Relation Member size fix

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/InvalidMultiPolygonRelationCheck.java
This reduces the default for the max shape points configurable in InvalidMultiPolygonRelationCheck from 2,000,000 to 300,000. This configurable controls which features are processed through the expensive overlap operations in the check. At the previous default the check took over 3.5 hours to process [this relation](https://www.openstreetmap.org/relation/5430065). By reducing the cap, all shards are now once again processed in under an hour each. 
Nothing major. A few less features may be processed through the overlap portion of the check. 
None
Tested about 200 countries. With the configuration value all shards took less than an hour to run for InvalidMultiPolygonRelationCheck. There were no differences in the features flagged between pre and post value change.
> InvalidMultiPolygonRelationCheck Max Shape Point Reduction

- config/configuration.json
- docs/available_checks.md
- docs/checks/missingRelationType.md
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/MissingRelationTypeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/MissingRelationTypeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/MissingRelationTypeCheckTestRule.java
MissingRelationTypeCheck is new Atlas Check development. Please refer to https://github.com/osmlab/atlas-checks/issues/454
Relations without Relation Type will be flagged
Create unit test to validate check functionality: Relation without type tag, One Member Relation, Disused Relations 
Passed.
|  UKR   |    56         |    56      |     100%       | 56   |   0  | 0%   |
|  FIN   |    32         |    32     |     100%       |   31 |   1 | 3.13%   |
|  IRL   |    23         |    23      |     100%       |   23 |   0 | 0%   |
|  ROU   |    17        |    17      |     100%       |   16 |   1 | 5.88%   |
|  CHN   |    176         |    176 …
> Missing relation type check

- build.gradle
- dependencies.gradle
- docs/checks/waterWayChecks.md
- docs/externalData.md
- gradle/quality.gradle
- src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
- src/main/java/org/openstreetmap/atlas/checks/base/ExternalDataFetcher.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/utility/ElevationUtilities.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheck.java
- src/test/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJobTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/ElevationUtilitiesTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/ElevationUtilitiesTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheckTest.java
This uses the same methods that the atlas files use to distribute additional data files.
Checks which use external data _must_ implement the ExternalDataUser interface. Depending upon needs, the implementer can either fetch locally immediately, fetch and parse, or do nothing (why would someone implement the interface and do nothing?).
Tested with HDFS (manually). Test setup for this consisted of a Raspberry Pi 4 with HDFS and a Mac to actually run the checks (I found that I needed to allocate a _lot_ of memory for external data, ~15G -- this only seemed to become an issue about the time that the geojson files were being written, most likely during the `reduceByKey` function).
To replicate errors/issues found during those tests, unit tests were written for `WaterWayCheck`, since that check …
> ExternalData: Use ResourceCache to get data

- build.gradle
- dependencies.gradle
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/BigNodeBadDataCheckTest.java
Bump atlas and atlas generator versions
Atlas: https://github.com/osmlab/atlas/compare/6.3.3...6.3.4
generator: https://github.com/osmlab/atlas-generator/compare/5.1.6...5.2.3
Jackson 2.6.7 -> 2.10.0 (dictated by new spark version brought in by generator)
Updated a unit test that was probably affected by https://github.com/osmlab/atlas/pull/708 from the new atlas version
Confirmed to run stably. Potential flag changes. 
NA
NA
> Atlas 6.3.4, Generator 5.2.3, Jackson bump

- docs/maproulette_upload.md
- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/ProjectConfiguration.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Survey.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/serializer/ChallengeDeserializer.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteClientTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
This addresses https://github.com/osmlab/atlas-checks/issues/429
3 new parameters are added to the MR Upload Command. They control project as well as fine-grained challenge discoverability (AKA enablement/visibility). 
The following defaults are changed:
Challenges and Surveys are disabled (undiscoverable) by default
Challenges are by default disabled
Same unit tests and sample project uploads using the MR upload command
Unit tests pass
Sample uploads:
`-discoverableProject=true`
`-undiscoverableChallenges=WaterbodyAndIslandSizeCheck`
`-discoverableProject=true`
`-discoverableChallenges=WaterbodyAndIslandSizeCheck`
`-discoverableProject=false`
`-discoverableChallenges=WaterbodyAndIslandSizeCheck`
`-discoverableProject=false`
`-discoverableProject=true`
`-discoverableChallenges=""`
> [MapRouletteUploadCommand] Configurable project and challenge discoverability

- src/main/java/org/openstreetmap/atlas/checks/utility/CommonMethods.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
AutoFix suggestion to "wrong roundabout direction" cases only. Please refer https://github.com/osmlab/atlas-checks/issues/387
Roundabouts with wrong direction will be suggested with AutoFix
1. Modify all existent cases for precise error handling
2. Add AutoFix verifier to "wrong direction" test cases
Passed
> Add AutoFix suggestion to "wrong direction" cases only.

- src/main/java/org/openstreetmap/atlas/checks/utility/CommonMethods.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/MissingRelationTypeCheckTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
Please refer to https://github.com/osmlab/atlas-checks/issues/460
MissingRelationTypeCheck - to generate less flags
OneMemberRelationCheck - to generate more flags
Create One Member Relation with Artificial Member (same OSM id)
CommonMethods - passed
MissingRelationTypeCheck - passed
OneMemberRelationCheck - passed
> Fix one member relation size

- src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
This fixes a bug where a check with a `countries.permitlist` (or the shortcut paramter `countries`) would always be enabled in those countries regardless of the global or their local `enabled` value. Thus when UnwalkableWaysCheck was run in SGP, even if it was set with `"enabled": false` it would still run. 
The correct checks will always be run. 
None
Tested setting the global enabled value to false and running checks in SGP and RUS. Before this fix UnwalkableWaysCheck and InvalidSignBoardRelationCheck would continue to respectively run in those countries. Ran again post fix and the runs failed in both countries with a no checks enabled error as expected.
> Fix Configuration Country Permitlist Bug

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityChecksCommandArguments.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheck.java
This makes the framework's external data input path configurable by adding a new Checks switch `externalDataInput`. This input path is fed into the ExternalDataFetcher (currently only used by WaterwayCheck for elevation data). Previously, external data was fetched from the SparkJob input path.
There is also a new configurable, `externalData.enabled`, which lives in BaseCheck and can be used to specify whether externalData should be used on a Check-by-Check basis. So in the configuration, you can decide if you want a certain Check to use externalData. This switch is largely symbolic, as the Check code itself must decide what to do given the switch value.
With an empty `externalDataInput`, we get the same behavior as before. With a user-supplied `externalDataInput`, we are just fetching …
> Add externalDataInput switch for Checks and make externalData configurable

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTestRule.java
Checks amount of OSM nodes in roundabout are at or above a certain number.
This is a request from our editors to flag roundabouts that are made of fewer than 9 OSM nodes.
We are also checking the angle between the segments of the roundabout.
None
Test for roundabouts with fewer than {threshold} OSM nodes
Test for roundabouts with angles greater than {threshold}
Fixed old tests that didn't account for OSM nodes/angles.
All results gathered were of just the new flags, old flags were commented out while gathering results.
A  note on the FP's: they are all due to Teardrop roundabouts.
|   ISO  | Total Flags | Sampled  | Sampling % | TP  |  FP | False Positive Rate |
|-------|-------------|------------|--------------|-----|-----| ------------------- |
|  ARG  |    51          |      24       | …
> [Improvement] MalformedRoundaboutCheck: Minimum OSM Nodes/Angles

- src/main/java/org/openstreetmap/atlas/checks/utility/CommonMethods.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
**Description:**
Handling reversed edges in CommonMethods.buildOriginalOsmWayGeometry. Please refer: #483
**Potential Impact:**
Supporting Reversed Edges.
**Unit Test Approach:**
Create unit test for Reversed edge.
Modified existent unit tests to pass new logic.
**Test Results:**
Passed
> Supporting reversed edges to build original OSM geometry.

- src/main/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/event/CheckFlagGeoJsonProcessor.java
- src/main/java/org/openstreetmap/atlas/checks/event/CheckFlagTippecanoeProcessor.java
- src/main/java/org/openstreetmap/atlas/checks/event/FileProcessor.java
- src/main/java/org/openstreetmap/atlas/checks/utility/UniqueCheckFlagContainer.java
- src/test/java/org/openstreetmap/atlas/checks/utility/UniqueCheckFlagContainerTest.java
This changes the way flag deduplication is done in the ShardedIntegrityChecksSparkJob to make it more distributable. 
Currently deduplicaiton is done using a reduce function to combine UniqueCheckFlagContainers. This results in all the flags for a country ending up on a single executor and thread.
This new system rework the UniqueCheckFlagContainer to contain only a single CheckFlag instead of many, and gives it a custom equals method that only compares the check name and unique identifiers of the flag. This allows for the use of sparks built in distinct method to remove duplicate containers in a distributed manor. By distributing this, and the following output step, each executor can be assigned less memory, as the maximum amount of data that any executor may need to store is drastically …
> ShardedIntegrityChecksSparkJob Deduplication Revamp

- config/configuration.json
- docs/available_checks.md
- docs/checks/similarTagValueCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/SimilarTagValueCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/SimilarTagValueCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/SimilarTagValueCheckTestRule.java
This check looks for similar values in a tag that are separated by a ‘;’.  
No impact
Added tests for duplicate tags and similar tags
|-----|-------------|------------|--------------|----|----| -------------------- |
|AUS|      491        |      491     |    100%        | 489 | 2  |         0.004%          |
|ARG|      24         |        24      |    100%        |  24 | 0   |             0%            |
|NZL|      28         |        28      |    100%        |  28 | 0   |             0%            |
|SWE|      44         |        44      |    100%        | 44 | 0   |             0%            |
|TUR|      79         |        79      |    100%        |  79 | 0   |             0%            |
The two FPs (both on …
> [New Check] SimilarTagValueCheck

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheckTest.java
Address issue https://github.com/osmlab/atlas-checks/issues/502
Change SharpAngelCheck so that the instructions list all points at which a sharp angle exist.
This will change the instructions only for SharpAngleCheck. Examples are below
Unit test was altered to test the new instructions.
Before the change this is what a single sharp angle issue looked like
https://maproulette.org/challenge/15097/task/69659510
After the patch is applied this is what that same task looks like
https://maproulette.org/challenge/16923/task/83503556
Before the patch this is what a multiple sharp angle task looks like
https://maproulette.org/challenge/15097/task/69659519
After the patch this is what a multiple sharp angle task looks like
https://maproulette.org/challenge/16923/task/83503558
(Note that in this …
> Change sharpAngle instructions

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheckTest.java
Resolves #501. For each edge we walk the way and gather all other edges. Looping over those edges we mark them as flagged and group all overlaps into one instruction.
Reduces the number of tasks for this check by grouping up flagged edges that are part of the same OSM way into the same task.
None added.
> OverlappingEdgeCheck: One task per way

- scripts/cloud-check-control/cloudAtlasCheckControl.py
When executing Challenge command in AWS script this will clear the output folder before syncing with S3
This speeds up map roulette upload command
Executed manually on three countries and it cleared the old data and synced the new folders correctly.
NA
> Clear output folder before sync in AWS script

- scripts/cloud-check-control/cloudAtlasCheckControl.py
Quick fix to make the "template" parameter in the AWS checks script to work properly.
This will make the parameter work. No impact to other code or functionality.
Executed script with the --template parameter
NA
> Fix template parameter in checks AWS script

- scripts/cloud-check-control/cloudAtlasCheckControl.py
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteClient.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/TaskLoader.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/TestMapRouletteConnection.java
This patch will add a new parameter (defaults to false) that if set to true will instruct the MapRouletteUploadCommand to purge all "Incomplete tasks" from any challenge that is being uploaded before uploading tasks to the challenge. Incomplete tasks are any task with a status of "created" or "skipped". These types of tasks have either not been processed or skipped for some reason. This purge parameter will delete them from the challenge before uploading a new task list so that any stale tasks that might have been fixed since the last update will be removed from the challenge. This prevents mappers from processing old tasks that have already been fixed and will (obviously) reduce the number of "already-fixed" task statuses.
This is a new parameter that if not specified will act exactly …
> Add purgeIncompleteTasks parameter to MapRouletteUploadCommand.

- src/main/java/org/openstreetmap/atlas/checks/validation/points/DuplicateLocationInPolyLineCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/DuplicateLocationInPolyLineCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/DuplicateLocationInPolyLineCheckTestRule.java
* Stop flagging closed loops (Edges and LineItems)
* Continue flagging closed loops (Areas -- the last location in an area line
_should not_ be the same as the first location in the area line)
This fixes #553 by not flagging terminating loops (Edges and LineItems). It continues to flag closed Area loops.
N/A
Added unit tests check that the last node does not flag the object when the last node already exists on the line.
Country | Flags | Sampled | False Positives
-|-|-|-
GBR|138|100%|0
Note: The atlas used for the test samples was from sometime between 2020-12-11 and 2020-12-13 -- some that I initially thought were FP turned out to have been fixed already.
> DuplicateLocationInPolyLineCheck: Fix #553, do not flag terminating loops

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
This updates the Challenge object used in the MapRouletteUploadCommand to reflect the change here: https://github.com/maproulette/maproulette2/pull/894
Also bumps a log from debug to error, to save a couple hours of debugging next time. 
None
None
Got a 400 error before the change when creating new challenges. After the change we are back to 200s.
> MapRoulette Challenge New API Key

- gradle.properties
hotfix and version bump to 6.1.21.1 due to PR https://github.com/osmlab/atlas-checks/pull/565
n/a
n/a
> hotfix 6.1.21.1

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/ShortSegmentCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/ShortSegmentCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/ShortSegmentCheckTestRule.java
1. Exclude atlas internal synthetic segments
2. Change instructions to use OSMId, and include startNode, endNode, like below:
"instructions": "1. This segment from startNode 268179597 to endNode 7392913442 on way 24673494 is short (length < 1 m) and node 268179597 has less than 3 connections."
3. Add a new unit test for internal synthetic segment.
I have run the fix for ISR,ISL,MLT,LUX,CPY,PER,NZL,MAR, the synthetic segments/nodes are removed successfully
> Fix bug #557 to exclude atlas internal segments

- .github/workflows/ci.yml
- config/configuration.json
- docs/checks/edgeCrossingEdgeCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTestRule.java
**Description:**
Please refer to:
check improvement: #466
bug fix: #473
**Potential Impact:**
Adding more options for crossing without intersections.
Can flag car navigable with car navigable (original, default)
Will flag car navigable with pedestrian (optional)
Will flag pedestrian with car navigable (optional)
Will flag pedestrian to pedestrian only (optional)
Will flag both car navigable, pedestrian with navigable, pedestrian (optional)
N/A still in draft
**Test Results:**
ISO | Sampled | TP | FP | False Positive Rate
-- | -- | -- | -- | --
USA | 1050 | 521 | 18 | 3.45%
BRA | 90| 90 | 9 | 8.89%
IND | 41 | 41 | 0 | 0%
IDN | 1| 1| 0 | 0%
GBR | 420 | 420 | 22 | 5.24%
**False Positives:**
(all below cases are handled with unit tests)
1. Combination of Layer=0 with …
> [Check Improvement] EdgeCrossingEdgeCheck improvement

- config/configuration.json
- docs/checks/lineCrossingWaterBodyCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/LineCrossingWaterBodyCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LineCrossingWaterBodyCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LineCrossingWaterBodyCheckTestRule.java
Please refer to: https://github.com/osmlab/atlas-checks/issues/561
mapping rules:
1. ways that end on the edge of a water body with the following tags should not be flagged as issues:
highway=(footway|bridleway|steps|corridor|path)
2. ways that cross into a water body (and end there) with the highway=steps should also not be flagged.
better handling for footway, bridleway, steps, corridor, path 
created unit tests to validate logic according to mapping rules 
passed
> lineCrossingWaterBodyCheck adding handling for footway, bridleway, steps, corridor, path

- src/main/resources/org/openstreetmap/atlas/checks/validation/tag/invalid-tags-check-regex-filter.json
This PR is to address OSMOSE 9005:
Class 9005001 "{0.key} with multiple values" 
Class 9005002 "empty value in semicolon-separated {0.key}" 
e.g. the following are examples of tags that are flagged by OSMOSE 9005:
- lanes with multiple values 
lanes = 1;2;3 
- name with multiple values 
name = Historica;Marker 
name = 4;22 
- highway with multiple values 
highway = traffic_signals;crossing 
- addr:street with multiple values 
addr:street = Fagerquist Rd; Wolf Ln; Pearce Lane 
- maxspeed with multiple values 
maxspeed = 40;50  
- water with multiple values 
water = service;cattle 
- telecom:medium with multiple values 
telecom:medium = fibre;copper 
- begins with semicolons
source = ;survey 
- ends with semicolons
cuisine = noodle;soba; 
- empty value in semicolon-separated tag …
> MultipleValuesInKeyCheck OSMOSE 9005 

- build.gradle
- scripts/cloud-check-control/cloudAtlasCheckControl.py
Add Support for DBs needed for new GenericTagCheck to AWS script
Without this the AWS script will not be able to execute the GenericTagCheck. This should not affect other checks.
This adds a dependency in the AWS VM to have ~/sqlite-jdbc-latest.jar available.
Since this depends on https://github.com/osmlab/atlas-checks/pull/357 I will keep it in draft until that PR is accepted.
Used this script to test the Generic Tag Check for QA
NA
> Add support for extra info input files in AWS script.

- config/configuration.json
- docs/available_checks.md
- docs/checks/duplicateRelationCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/DuplicateRelationCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/DuplicateRelationCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/relations/DuplicateRelationCheckTestRule.java
Add Duplicate Relation Check, this check flags multiple members Relations in OSM that have the same OSM tags and the same members with same roles.
As discussed,  this check excludes one member relations and leave that for the OneMemberRelationCheck for avoiding one member relations overlap. 
| ISO | Sampled | TP | FP | False Positive Rate |
|-----|----------|----|----| ------------------- |
|  ARG |   99 |    97     |   2 |  2%   |
|  AUS |   100 |    100     |   0 |  0%   |
|  ISR |   56 |    56     |   0 |  0%   |
|  MLT |   7 |    7     |   0 |  0%   |
|  NZL |   49 |    49     |   0 |  0%   |
|  SWE |   61 |    61     |   0 |  0%   |
|  TUR |   51 |    45     |   6 |  11%   |
The False Positive flagged relations in ARG and TUR are actually caused by those relations atlas objects …
> Add Duplicate Relation Check

- config/configuration.json
- docs/checks/genericTagCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/GenericTagCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/GenericTagCheckTest.java
GenericTagCheck: Fail fast when databases cannot be read
In the interest of allowing people to not use the TagInfo db, i.e., if they
want to find tags without entries in wikidata, there are some new
*undocumented* options.
People who depend upon GenericTagsCheck to always run will have to add an undocumented config option to the configuration json.
N/A
> GenericTagCheck: Fail fast when databases cannot be read

- docs/checks/connectivityCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheckTestRule.java
Please refer to first PR for the comments: https://github.com/osmlab/atlas-checks/pull/608
Description:
Please refer to #504
ConnectivityCheck scope is reduced by removing duplicated logic of crossing edges to EdgeCrossingEdge check.
Nodes that too close but connected to two+ edges won't be flagged.
Corresponded unit tests: invalidDisconnectedNodesCrossingTest, invalidDisconnectedEdgeCrossingTest from ConnectivityCheck moved to EdgeCrossingEdge.
Test Results:
passed
> ConnectivityCheck flags parallel way as connectable

- config/configuration.json
Until this check can be fixed so that it doesn't take so long I propose that we disable the check by default in the configuration. 
This won't have any other effect on the actual check and if you want to execute that specific check then you can still do it. It will only change the default atlas checks that are executed when the configuration.json is used.
> Disable DuplicateMapFeatureCheck by default.

- config/configuration.json
Re-disables DuplicateMapFeatureCheck, as run times are still way too high, even after https://github.com/osmlab/atlas-checks/pull/616.
I actually misinterpreted the run times the first time this check was enabled, thinking the longest shard took 22 minutes. It in fact too 22 hours. Times are down slightly now, with the worst shard being 15 hours. However any shard should be taking more than about 5 minute. There are over 1500 shards currently that take more than an hour. 
Fix overall execution time. 
None
None
> Redisable DuplicateMapFeatureCheck

- src/main/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/ConnectivityCheckTestRule.java
please refer to https://github.com/osmlab/atlas-checks/issues/627
More true dead end cases will be flagged. 
Added unit test covering reversible edge. 
Both reported cases are flagging now:
[CheckFlag: 6230687868000000, 1. Node 6230687868 is likely supposed to be connected to: way 525179930]
[CheckFlag: 7148640414000000, 1. Node 7148640414 is likely supposed to be connected to: way 855789796]
> ConnectivityCheck Dead End improved logic

- build.gradle
- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/flag/serializer/CheckFlagDeserializer.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Task.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/cooperative_challenge/CooperativeChallengeOperation.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/cooperative_challenge/GeometryChangeOperation.java
- src/main/java/org/openstreetmap/atlas/checks/utility/OpenStreetMapCheckFlagConverter.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheck.java
- src/test/java/org/openstreetmap/atlas/checks/flag/serializer/CheckFlagDeserializerTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/TaskTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/TaskTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/cooperative_challenge/GeometryChangeOperationTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/cooperative_challenge/GeometryChangeOperationTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/lines/WaterWayCheckTest.java
Add fix suggestions for wrong way waterways, when elevation data suggests that it is going in the wrong direction.
This fixes #403 .
~This depends upon https://github.com/osmlab/atlas/pull/729 (without this PR, only \~8 points can actually be changed).~
~This depends upon https://github.com/osmlab/atlas-generator/pull/179 and https://github.com/osmlab/atlas/pull/750 for OSC upload functionality.~
N/A
All current unit tests now check to ensure that there is or is not a fix suggestion present. When there is a fix suggestion present, the before/after views are compared, and are expected to be different. Due to the change between the before/after views, it is expected that reversing a collection of points will cause the before/after view collections to be equal.
MapRoulette testing mostly …
> WaterWayCheck: Add autofix suggestion (geometry)

- config/configuration.json
- docs/available_checks.md
- docs/checks/invalidTurnLanesValueCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTurnLanesValueCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTurnLanesValueCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTurnLanesValueCheckTestRule.java
This check flags roads that have invalid `turn:lanes` tag values.
Valid values contain keywords found in 
https://github.com/osmlab/atlas/blob/dev/src/main/java/org/openstreetmap/atlas/tags/TurnTag.java
```java
enum TurnType
{
LEFT,
SHARP_LEFT,
SLIGHT_LEFT,
THROUGH,
RIGHT,
SHARP_RIGHT,
SLIGHT_RIGHT,
REVERSE,
MERGE_TO_LEFT,
MERGE_TO_RIGHT,
NONE;
}
String TURN_LANE_DELIMITER = "\\|";
String TURN_TYPE_DELIMITER = ";";
```
e.g. "turn:lanes":"through|through|right" is valid
e.g. "turn:lanes":"through|through|righ" is not valid
1. The way [id:730457851](https://www.openstreetmap.org/way/730457851) has an invalid `turn:lanes` 
2. The way [id:836279618](https://www.openstreetmap.org/way/836279618) has an invalid `turn:lanes:forward`
In [Atlas](https://github.com/osmlab/atlas), OSM elements are …
> Turn Lanes Value Check

- build.gradle
- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/utility/ElevationUtilities.java
- src/main/java/org/openstreetmap/atlas/checks/utility/SQLiteUtils.java
Also, move classes using log4j to slf4j.
This should have no effect on runtime logging.
See also
* https://github.com/osmlab/atlas/pull/780
* https://github.com/osmlab/atlas-generator/pull/196
> Update log4j to 2.17.1

- dependencies.gradle
- docs/maproulette_upload.md
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommand.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
This adds a new optional parameter to the MapRouletteUploadCommand to select whether to use the ISO code or country display name in uploaded challenge titles. 
Currently challenge titles are created with the pattern "Country Display Name - Check Name". When this new parameter is true, which it is by default, this same pattern will be used. When the parameter is false the pattern will be "ISO - Check Name".
Additionally this adds some missing docs, and bumps the atlas version.
This should be fully backwards compatible. 
Added a unit test for when the param is false. 
Ran three test runs with the param true, false, and not given. 
True:
False:
Default:
> MapRouletteUploadCommand Challenge Country Name Parameter

- gradle.properties
Bumped atlas checks gradle.properties to 6.3.4-SNAPSHOT
> Version Bump

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteClient.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteCommand.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteUploadCommandTest.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/TestMapRouletteConnection.java
This adds a new optional `-proxy` parameter to the MapRouletteCommand. The proxy is defined in the format `scheme://host:port`, and is fed through to the underlying apache HttpClients. 
A number of new constructors are created to achieve this, but everything is backwards compatible. 
None, everything is backwards compatible.
Updated the test connection class, and added a unit test to ensure the proxy param is parsed correctly. 
Tested running with a proxy from behind a restricted network.
Project, challenges, and tasks were created successfully:
> MapRouletteCommand Optional Proxy Parameter

- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Challenge.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/ChallengeSerializationTest.java
This adds the `isArchived` field to the Challenge class, and adds it as a value in the challenge json. For now it is set to always be false, as challenges must be unarchived for tasks to be uploaded to them through the API. 
This will cause any archived challenges to be unarchived by the MapRouletteUploadCommand before it attempts to upload tasks to the given challenges. This is useful for dealing with the new challenge auto-archiving after 6 months of inactivity.  
Challenges will be unarchived by the MR Upload command before attempting to upload tasks to them.
Added the new field in the serialization unit test. 
Tested uploading to an archived challenge before and after this change. Before, the challenge remained archived and no tasks were uploaded. After, the challenge was unarchived …
> MapRoulette Challenge isArchived

- src/main/java/org/openstreetmap/atlas/checks/maproulette/data/Task.java
- src/test/java/org/openstreetmap/atlas/checks/maproulette/data/TaskTest.java
The latest Maproulette API update now requires task endpoint requests to include a "errorTags" key. This adds that with a value of an empty string. Currently all task uploads will silently fail because of this. 
Note for reviewers:
The PointInformation subclass was moved to make checkstyle happy. 
Fix MR uploads
Added a unit test to check that the new key is added. 
Tested uploading tasks with the command before and after the change. Not tasks were uploaded before, and they are uploaded after.
> MapRoulette Upload Command New Required Task Key

- config/configuration.json
- src/test/java/org/openstreetmap/atlas/checks/validation/geometry/InvalidGeometryCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/geometry/InvalidGeometryCheckTestRule.java
Description:
please refer to: https://github.com/osmlab/atlas-checks/issues/645
implemented in check Configuration. attraction->!roller_coaster&roller_coaster->!
OSM objects with tags "roller_coaster=*" and "attraction=roller_coaster" will be filtered out from check.
Created unit test for "roller_coaster=*" and "attraction=roller_coaster" cases.
Test Results:
passed.
> InvalidGeometryCheckTest add roller coaster logic

- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
There is a bug with the purge incomplete tasks switch for the maproulette upload command. When this switch is true a `statusFilters` parameter is added to the shared url builder used in MapRouletteConnection. This addition persists and increases every time a task is deleted by the purgeIncompleteTasks method. The result is that urls start to look like the following:
```
/api/v2/challenge/14150?statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&statusFilters=0%2C3&sta …
```
> MapRoulette Upload Purge Incomplete Bug

- config/configuration.json
- docs/available_checks.md
- docs/checks/highwayIntersectionCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/HighwayIntersectionCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/HighwayIntersectionCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/HighwayIntersectionTestCaseRule.java
Picked up where #643 left off.
Changes are:
* Flagging the highway and the node(s) that intersects with the powerline/waterway instead of the powerline/waterway
* Flags the way instead of just the edge
|  ARG   |    10         |    10      |     100%       |   10 |   0 | 0%   |
|  AUS |    9         |    9      |     100%       |   9 |   0 | 0%   |
|  TUR |    18         |    18      |     100%       |   18 |   0 | 0%   |
> Highway Intersection Check

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTestRule.java
For some time now the EdgeCrossingEdgeCheck has suffered from very poor efficiency in processing features that have a significant number of invalid intersections. An example is this feature at version 5: https://www.openstreetmap.org/way/1043498633. This has regular increased the overall runtime for checks execution to 6+ times the time it normally takes. 
This stemmed from the way the check would walk a network of invalid intersections a number of times equal to the number of edges in the network. This design was originally implemented to resolve a possible nondeterminism issue, that in review did not really exist. However, there were a couple of other beneficial things added with this. Checks were made simpler, and marked the exact point of intersections. These improvements have both …
> EdgeCrossingEdgeCheck Rework for Execution Time

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheckTestRule.java
Describe the bug
FloatingEdgeCheck is supposed to ignore edges inside of airports. It currently does this by checking for overlap with areas that have an aero way tag. This leaves out the many airports that are modeled as multi-polygon relations. This PR enhanced the check to test overlap with multi-polygon airports.
For example, it should not flag  this way -> 874001205
-NA-
**FloatingEdgeCheck:**
**Country  |  baseline  |  PR_test_result**
AGO           	10                    9
ARE            	16                    13
BRA            	76                   75
CHE           	 29                  27
CHN         	10194             10190
CUB              3                     2
CZE              3                     2
ESH              4                      3
GAB             6 …
> Handled FloatingEdgeCheck Airport Relations Bug

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/SinkIslandCheckTestRule.java
This update is to resolve two issues with the SinkIslandCheck.
This fixes https://github.com/osmlab/atlas-checks/issues/585. It does this by making car ferries a valid terminus for a road network. Thus ways like the following are no longer flagged:
This also fixes an issue with the way car navigability was derived from the vehicle, motor_vehicle, and motorcar tags. These tags act in a hierarchical fashion. This was previously ignored, so that if any of these tags had a navigable value the other's values were irrelevant. 
Example, this way was flagged because it had vehicle=yes and its motor_vehicle=permit was ignored while the connected ways just had motor_vehicle=permit:
None
Added unit tests for car ferries, pedestrian ferries, and car access hierarchy. 
Analysis was done on the …
> SinkIslandCheck Ferry and Car Access Update

- config/configuration.json
- docs/available_checks.md
- docs/checks/enclosedBuildingNodeCheck.md
- docs/checks/loneBuildingNodeCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/points/EnclosedBuildingNodeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/LoneBuildingNodeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/EnclosedBuildingNodeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/EnclosedBuildingNodeCheckTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/LoneBuildingNodeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/LoneBuildingNodeCheckTestRule.java
**LoneBuildingNodeCheck**: The purpose of this check is to convert a Node with building tag into Building Footprint polygon (enclosed Way or Relation).
**EnclosedBuildingNodeCheck**:The purpose of this check is to remove building tag from the Node that is fully geometrically enclosed into Building Area. |
For more Check information with used cases and OSM wiki reference please refer to:
https://github.com/osmlab/atlas-checks/issues/682
https://github.com/osmlab/atlas-checks/issues/681
EnclosedBuildingNodeCheck: Better building tag mapping according to OSM common practice. 
LoneBuildingNodeCheck: Increasing building footprint coverage.  
**Note**: QA validation release "daylight_2022-06-18". Vast majority of FP cases already been fixed in OSM by community.    
**LoneBuildingNodeCheck**
| …
> [New Atlas Check] LoneBuildingNodeCheck and EnclosedBuildingNodeCheck 

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/LevelCrossingOnRailwayCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LevelCrossingOnRailwayCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LevelCrossingOnRailwayCheckTestRule.java
please refer: 
1) https://github.com/osmlab/atlas-checks/issues/672
2) https://github.com/osmlab/atlas-checks/issues/675
3) Atlas version 7.0.6 bump (Atlas version to handle above cases)
Nodes with valid crossing won't be flagged.
Simulate test for tram_level_crossing and disused:railway cases   
passed
> LevelCrossingOnRailwayCheck adding logic for tram_level_crossing and disused:railway  
