- src/main/java/org/openstreetmap/atlas/checks/persistence/SparkFileHelper.java
I am updating `save` method and making it more robust to random I/O failures by utilizing `Retry` class. I added a static variable called `IO_RETRY` and used `run` method of `Retry` class while executing save operations. If a save operation fails, then it will retry for 5 times max while waiting 5 seconds in between retry operations.
Other changes are related to style. Spotless styler rearranged the order of two `save` methods.
Tested this locally with a method that fails to write a file randomly several times but succeeds the fifth time regardless.
> Make I/O operations more robust in SparkFileHelper

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheckTestRule.java
This check looks for edges that cross other edges but do not contain a shared node.
> Added check EdgeCrossingEdgeCheck

- config/configuration.json
- docs/checks/sharpAngleCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SharpAngleCheck.java
The messaging for the SharpAngleCheck was a little bit inaccurate, so this PR simply updates the messaging.
> Updating the messaging for SharpAngleCheck to be more accurate.

- README.md
The "Docker Sandbox" section was in error and no such component was included in this project.
> Removing errant documentation

- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/SelfIntersectingPolylineCheck.java
PR contains minor helper function refactoring. 
@mertemin
> SelfIntersectingPolylineCheck cleanup

- config/configuration.json
- docs/checks/duplicatePointCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/points/DuplicatePointCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/DuplicatePointCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/points/DuplicatePointCheckTestRule.java
The Duplicate Point check flags Points in OSM that share the same location. 
This PR includes flag logic, documentation, configuration, and unit tests.
> Duplicate Point Check

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
This pull request makes changes solely to the instruction message associated with Floating Edge check flags.
> Floating Edge Check Enhancements

- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
This PR is making a simple change to log run time as an info message. Other change is done by Eclipse.
> Log time to execute message as info

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/distributed/AtlasDataSource.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/event/CheckFlagGeoJsonProcessor.java
- src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteClient.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/UnusualLayerTagsCheck.java
- src/test/java/org/openstreetmap/atlas/checks/event/CheckFlagGeoJsonProcessorTest.java
This includes updates to remove new compilation errors, maproulette spotless apply, as well as NPE protection in one test.
> Use latest Atlas & Atlas Generator dependencies

- build.gradle
- docs/cluster.md
Update document to add more details of running checks on spark cluster. This document is by no means to provide a complete, step by step instruction, but to hope to help users get started, better understand the challenges and contribute to improving over time.  #61
> document: running checks on spark cluster

- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
IntersectionUtils.findIntersectionPercentage() contains similar code to IntersectingBuildingsCheck.findIntersectionType(). So, this PR replaces one with the other.
None.
No new functionality was added, so no new unit tests were added. I also ran IntersectingBuildingsCheck on an HKG Atlas using both the up-to-date dev branch and this branch. 
All tests are passing. Both check runs produce the same number of flags and a random sampling of the flags are identical. There were over 3000 flags, so checking each flag is not practical. 
------
In doubt: [Contributing Guidelines](CONTRIBUTING.md)
> Intersecting Buildings Check: Refactor to use new IntersectionUtils class

- README.md
This is a cosmetic change to have the Sonar badge in the readme.
N/A
N/A
N/A
> Update Sonar badge

- gradle.properties
increase version number to 4.0.5 after release
n/a
n/a
n/a
> increase version after release

- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SignPostCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
update atlas to version 5.2.0 and use recommended method to get instance of TaggableFilter.
n/a
run all existing unit tests
passed.
> update atlas to 5.2.0

- gradle.properties
increase version number after release
n/a
run existing tests
pass
> increase version number after release

- gradle.properties
increase version number after release
n/a
n/a
n/a
> increase version number after release 

- gradle.properties
Increment version. Released 4.0.7
> increment version

- dependencies.gradle
- gradle.properties
- src/main/java/org/openstreetmap/atlas/checks/distributed/AtlasDataSource.java
Update the atlas generator version
> Generator update

- README.md
Fix duplicate word on paragraph 27.  Plus minor formatting proposals
There is no  potential impact over any file of this project. There is no break on code.
There is no unit test approach in this pull request. It begins and ends on this unique file of this repo.
There is no test done.
> Fix duplicate word on paragraph #27

- .travis/deploy.sh
- build.gradle
- gradle.properties
- gradle/createStagingId.sh
- gradle/deployment.gradle
- gradle/dropSonatype.sh
- gradle/nexus_description.xml
- gradle/releaseSonatype.sh
- gradle/uploadAndRelease.sh
This is a followup of #105. Same comments!
This PR includes the closing and releasing of repositories as well.
Reference issue: https://github.com/travis-ci/travis-ci/issues/9555
Refer to #105 
N/A
Tested locally
> [HACK] Include closing and releasing of Sonatype Repositories

- gradle/deployment.gradle
- gradle/dropSonatype.sh
- gradle/releaseSonatype.sh
- gradle/uploadAndRelease.sh
- gradle/uploadToNexus.sh
Followup to #105 and #106.
N/A
N/A
Tested locally
> [HACK] Final fixes for Travis

- gradle.properties
Increment version after release
> increment version after release

- gradle.properties
> bump version after release

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksCommand.java
- src/main/java/org/openstreetmap/atlas/checks/event/MetricFileGenerator.java
Update the dependencies and handle the effect of the changes in Atlas. 
Needed to mirror the removing of a dependency: https://github.com/osmlab/atlas/pull/318/files
Needed to handle "NONE" and a file suffix option: https://github.com/osmlab/atlas/pull/317
Potential that Unit tests didn't cover issues that this may cause. But the first change is identical to what has been tested in the Atlas repository and the second issue was caught by a unit test and the change passes.
> Update dependecies, handle changes

- gradle.properties
Bump version after release
N/A
> bump version to 5.0.6

- gradle.properties
> Bump Version to 5.0.7

- dependencies.gradle
- update atlas to 5.6.1 and atlas-generator to 4.3.0.
none as long as there is no breaking change in the new atlas version.
run all existing unit tests
pass
> update atlas to 5.6.1

- gradle.properties
bump version to 5.0.8
n/a
n/a
n/a
> bump version to 5.0.8

- dependencies.gradle
- gradle.properties
update atlas to 5.6.4
update atlas-generator to 4.3.1
n/a
run existing tests
pass
> update atlas version

- gradle.properties
> bump version to 5.0.10

- gradle.properties
> Bump version to 5.1.0

- gradle.properties
> bump version to 5.1.1

- gradle.properties
> bump version to 5.1.2

- dependencies.gradle
Update atlas and atlas-generator versions
built and ran locally 
successful
> update dependency versions

- gradle.properties
> bump version to 5.1.3

- dependencies.gradle
Update atlas version: 5.6.7 -> 5.7.1
Update atlas-generator version: 4.3.3 -> 4.3.5
N/A
Local gradle build  
The local gradle build has passed
> dependency updates

- dependencies.gradle
Bumping atlas version 5.7.1 -> 5.7.5
**Testing Approach:**
Built locally
**Test Results:**
Built successfully
> Atlas version bump

- gradle.properties
bump version to 5.1.7 after releasing 5.1.6
> bump version to 5.1.7

- dependencies.gradle
update atlas version to 5.8.0
built locally 
successful
> update atlas version to 5.8.0

- gradle.properties
Bump version to 5.1.9 after releasing 5.1.8
> bump version to 5.1.9

- docs/checks/generalizedCoastlineCheck.md
Update generalizedCoastlineCheck.md to reflect the most recent updates to Generalized Coastline check.
None
NA
NA
> [Doc update] Add source=pgs info to generalizedCoastlineCheck.md

- dependencies.gradle
Upgrade atlas to 5.8.4 in dependency
ran locally
successful
> Upgrade Atlas to 5.8.4

- gradle.properties
bump version to 5.2.0 after releasing 5.1.9
> bump version to 5.2.0

- dependencies.gradle
Bringing in the latest atlas release
No downstream impact
Unit tests pass
Unit tests pass
> Bump Atlas version to 5.8.7

- gradle.properties
Bumping version to 5.2.1 after release of 5.2.0
> Bump to 5.2.1

- src/main/java/org/openstreetmap/atlas/checks/atlas/predicates/TagPredicates.java
- src/main/java/org/openstreetmap/atlas/checks/atlas/predicates/ValuePredicates.java
- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/base/CheckResourceLoader.java
- src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksCommand.java
- src/main/java/org/openstreetmap/atlas/checks/configuration/ConfigurationResolver.java
- src/main/java/org/openstreetmap/atlas/checks/constants/CommonConstants.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/AtlasDataSource.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/FloatingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SnakeRoadCheck.java
- src/test/java/org/openstreetmap/atlas/checks/atlas/predicates/ValuePredicatesTest.java
Sonar reported on blocker, critical and major issues. This PR is created to address blocker, critical and few major issues.
**Issues addressed in this PR:**
1. src/.../atlas/checks/atlas/predicates/TagPredicates.java
Move constants to a class or enum.
2. src/.../atlas/checks/atlas/predicates/TypePredicates.java
Move constants to a class or enum.
3. src/.../atlas/checks/atlas/predicates/ValuePredicates.java
Move constants to a class or enum.
4. src/.../atlas/checks/base/BaseCheck.java
Make "flaggedIdentifiers" transient or serializable.
5. src/.../atlas/checks/base/CheckResourceLoader.java
No need to call "toString()" method as formatting and string conversion is done by the Formatter.
6. src/.../atlas/checks/commands/AtlasChecksCommand.java
Catch Exception instead of Throwable.
7. …
> Sonar fixes

- gradle.properties
bump version to 5.2.2 after releasing 5.2.1 
> bump version to 5.2.2

- .travis/sonar.sh
- build.gradle
- gradle/quality.gradle
Fix sonar test coverage, similar as what was done in https://github.com/osmlab/atlas/pull/480
Sonar reports accurate again
N/A
N/A
> Fix sonar test coverage

- config/configuration.json
This will disable the DuplicateWaysCheck. OverlappingEdgeCheck will replace what this check was identifying.
Number of check flags will be 0 but will be reflected in OverlappingEdgeCheck.
Ran locally.
0 check flags produced.
> Disable DuplicateWaysCheck

- gradle.properties
bump version to 5.2.3 after releasing 5.2.2.
> bump version to 5.2.3

- docs/bestpractices.md
Fixed typo on line 16
There is no side-effects, no break on code
There is no need of unit test approach
There is no break on code
> Fixed typo on line 16

- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LineCrossingWaterBodyCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LineCrossingWaterBodyCheckTestRule.java
This adds unit tests for the LineCrossingWaterBodyCheck. This check was recently added to Atlas Checks in #234 .
No impact
Unit tests 
Tests pass as expected
> Add LineCrossingWaterBody unit tests

- dependencies.gradle
Description:
Update atlas version to 6.0.1
built locally
Test Results:
successful
> updated dependency to 6.0.1

- gradle.properties
Description:
Update gradle.properties version to 6.0.1
built locally
Test Results:
successful
> Bumping gradle.properties to 6.0.1

- dependencies.gradle
Bump from Atlas version 6.0.2 to 6.1.0.
Updated version of Atlas.
`./gradlew clean build`
Successful.
> Bump to Atlas version 6.1.0

- gradle.properties
> Bump to 6.0.3

- dependencies.gradle
Bump atlas to 6.1.3
Brings in latest changes from atlas
> bump atlas to 6.1.3

- gradle.properties
Bump atlas-checks version to 6.0.4
> Bump version to 6.0.4

- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheck.java
to fix bug https://github.com/osmlab/atlas-checks/issues/302 
Details: eliminate traversing via reversed Edges
List potential impact to downstream libraries here (ex. atlas-checks, atlas-generator)
Describe unit tests being added with that PR.
> fix traversing via reversed edges.

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the current pull request template with some additional details on what to be included under the "Test Results" for new checks.
None
NA
NA
> Updates to Pull Request Template

- gradle.properties
Updating the version to 6.0.10 for next release
> Updating the version to 6.0.10 for next release

- dependencies.gradle
Updated dependencies.gradle to Atlas version 6.2.2 for version bump to Atlas Checks 6.0.10
> Updated dependencies.gradle to Atlas version 6.2.2

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTestRule.java
Adding conditions to handle enclosed Area in roundabout. For full discussion please refer to https://github.com/osmlab/atlas-checks/issues/318
N/A
Created unit test for following conditions:
1) Enclosed Navigable Roads
2) Enclosed Navigable Roads with Area Tag
3) Enclosed Multilayer Navigable Roads, Bridges & Tunnels.  
Passed
> Adding additional logic and unit tests to MalformedRoundaboutCheck

- dependencies.gradle
Updated atlas version to 6.2.4 in dependencies.gradle
N/A
N/A
N/A
> Updated atlas version to 6.2.4

- gradle.properties
> Bump version to 6.0.12

- docs/tutorials/tutorial1-PoolSizeCheck.md
Made config values doubles and added imports that were missing.
None (documentation only)
None (documentation only)
None (documentation only)
> A few documentation fixes that tripped me up

- src/main/java/org/openstreetmap/atlas/checks/base/BaseCheck.java
- src/main/java/org/openstreetmap/atlas/checks/base/Check.java
- src/main/java/org/openstreetmap/atlas/checks/commands/JSONFlagDiffSubCommand.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJob.java
- src/main/java/org/openstreetmap/atlas/checks/utility/IntersectionUtilities.java
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/WaterbodyAndIslandSizeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/BigNodeBadDataCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/DuplicateWaysCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/points/AddressPointMatchCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/ConflictingAreaTagCombination.java
- src/main/java/org/openstreetmap/atlas/checks/validation/tag/ShortNameCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/verifier/ExpectedCheckVerifier.java
- src/test/java/org/openstreetmap/atlas/checks/distributed/ShardedIntegrityChecksSparkJobTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/tag/ConflictingTagCombinationCheckTest.java
This updates some code to use new (Java 8+) features, and fixes an NPE that was noticed.
This also has some modernization efforts as well (so generics are used in some locations). This may require some downstream projects to `atlas-checks` to recompile, but should not require any significant source code changes.
N/A -- this is largely cosmetic changes (but ones that will be useful).
> Code smells (sonar/NPE)

- dependencies.gradle
> Updating the dependencies.gradle with the latest atlas release

- dependencies.gradle
Use the latest atlas version
Will unblock a few checks
Describe unit tests being added with this PR.
Describe other (non-unit) test results here. In case of a new check or enhancements to existing 
checks, please add details on how many countries the check was tested on,
total flag counts, FP rate etc. (see below example).
> Update to atlas 6.2.10

- gradle.properties
6.1.3-SNAPSHOT to 6.1.4-SNAPSHOT
> Version bump for next release

- .github/ISSUE_TEMPLATE/fix-suggestions.md
This adds the template of fix suggestions
N/A
N/A
N/A
> Create template for fix suggestions

- gradle.properties
> Bump version for next release

- src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidTagsCheck.java
This fixes a bug in InvalidTagsCheck that was causing IndexOutOfBoundsExceptions in heavily distributed runs. Each time the check was instantiated it read in the custom instructions and added them to a static List of Strings. This caused the static list to grow each time, but spark had trouble communicating that to each executor causing the IndexOutOfBoundsExceptions.
Only impacts the one check.
None
Tested a large distributed run with the changes and the exceptions were gone and flags for InvalidTagsCheck were up.
> InvalidTagsCheck Static Instructions Bug

- gradle.properties
Bumping the version for the next release. From 6.1.6 to 6.1.7.
> 6.1.7 bump

- scripts/cloud-check-control/cloudAtlasCheckControl.py
The following changes have been made to the aws script:
1. Bump version to 0.3.0
2. Remove critical log when finishing
3. Switch output parameter to input for challenge command
4. Make jar and config required parameters
5. Remove s3fs mount logic.
6. Add log to indicate the command to run if disconnected while executing.
7. Add "info" parameter to allow to inject info into an "INFO" file in the output directory.
8. Made input, output, config, and jar parameters require the s3:// preface
9. Remove all single "-" parameters. 
Will require some small changes to the call to execute aws atlas checks.
NA
Executed a few times with different parameter combinations.
> Make some incremental fixes to the aws script

- scripts/cloud-check-control/cloudAtlasCheckControl.py
This changes are to fix a number of small issues with the aws scripts and to fix issues found with another code review
This should have no impact on the existing aws scripts.
Scripts were used to execute atlas checks in AWS
All good
> Aws Script fixes to support automation

- config/configuration.json
- docs/available_checks.md
- docs/checks/concerningAngleBuildingCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/ConcerningAngleBuildingCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/ConcerningAngleBuildingCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/ConcerningAngleBuildingCheckTestRule.java
This check attempts to flag building who have angles between 80 and 89.7 degrees or between 90.3 and 100 degrees that need to be squared.
| ISO     | Sampled |    TP        | FP    | False Positive Rate |
|--------|----------|------------|------|----------------------|
|  ARG   |    300     |    300       |   0    |          0%                |
|  AUS   |    300     |    300       |   0    |          0%                |
|  CHL   |    300     |    300       |   0    |            0%               |
|  COL   |    300     |    299       |   1    |           0.003%           |
|  ECU   |    300     |    299       |   1    |            0.003%          |
Resolves #450
> Concerning angle building check

- gradle.properties
> Bump version to 6.1.11

- src/main/java/org/openstreetmap/atlas/checks/utility/CommonMethods.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/InvalidPiersCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheck.java
- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutMissingTagCheck.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTest.java
- src/test/java/org/openstreetmap/atlas/checks/utility/CommonMethodsTestRule.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutMissingTagCheckTestRule.java
Please refer: https://github.com/osmlab/atlas-checks/issues/487
consolidated logic. better unittest coverage.  
N/A
1. Execute following Checks before and after change:
- RoundaboutMissingTagCheck
- InvalidPierseCheck
- OverlapingEdgeCheck
2. Ensure the identical results
USA Metro Cities (e.g. San Francisco, New York, Seattle, etc)
Great Britain: Metro Cities (e.g. Liverpool, London, Manchester etc)
Brazil: San Paulo, Rio
Indonesia: Jakarta, Surabaya, Medan
India: Mumbai, Kolkata, Delhi
Output from checks before and after is identical.
> remove redundant code utilizing CommonMethods

- docs/checks/malformedRoundaboutCheck.md
- docs/checks/roundaboutMissingTagCheck.md
Added AutoFix section to check documentation. 
N/A 
N/A
N/A
> AutoFix section added to documentation.

- dependencies.gradle
This updates Atlas and atlas generator to the latest version 
Fix issues found in latest atlas
Executed a test check to make sure it sill built and could execute checks
Able to generate atlas checks for NZL for one check
> update atlas and generator

- dependencies.gradle
- gradle.properties
> Bump atlas to 6.4.7

- gradle.properties
Bumping from 6.1.20 to 6.1.21 for the next release.
> bumping to 6.1.21 for next release

- src/main/java/org/openstreetmap/atlas/checks/validation/tag/FixMeReviewCheck.java
Just updating check to reflect Atlas repo interface addition
> implemented FixMe interface from Atlas repo

- gradle.properties
atlas-checks version bump to 6.2.0 for next release
rdar://78776369 (Luigi 06/01-06/09)
> 6.2.0_version_bump

- dependencies.gradle
osmlab/atlas-checks release 6.2.0 with atlas version 6.5.2
rdar://79316284 (Luigi 06/15 - 06/23)
> 6.2.0_release

- gradle.properties
6.2.1 atlas-checks version bump for next release
rdar://79316284 (Luigi 06/15 - 06/23)
> 6.2.1_versionbump

- dependencies.gradle
changed version from atlas 6.5.2 to atlas 6.5.3
N/A
N/A
N/A
> changed version from atlas 6.5.2 to atlas 6.5.3

- config/configuration.json
- docs/checks/levelCrossingOnRailwayCheck.md
- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/LevelCrossingOnRailwayCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LevelCrossingOnRailwayCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/LevelCrossingOnRailwayCheckTestRule.java
Please refer to: https://github.com/osmlab/atlas-checks/issues/577
1) assigning "disuse" to a Node if railway is disused.
2) adding minimum highway type for configuration.json
created unit test for following scenarios:
- minimum highway type
- railway=disuse case 
passed
> LevelCrossingOnRailwayCheck refinement

- docs/available_checks.md
- docs/checks/unknownHighwayTagCheck.md
Updating documentation to refelct check better
> updating documentation to refelect this check more accurately.

- gradle.properties
updated version to from 6.2.2 to 6.2.3
> updated version to 6.2.3

- dependencies.gradle
> updated atlas version

- src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheckTestRule.java
Please refer: https://github.com/osmlab/atlas-checks/issues/637 
Adding more handling to Pedestrian Area tagging
Added highway=footway to existent `testPedestrianAreaOverlapPedestrianEdgeAtlas`
Passed.
> OverlappingEdgeCheck Pedestrian Area Definition

- src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsTestCaseRule.java
See: #408 
N/A
Added asserts for correct building OSM id being in the fix suggestion.
Resolves: #408
> [Fix Suggestions] Intersecting Buildings Check

- docs/checks/invalidTagsCheck.md
- src/main/resources/org/openstreetmap/atlas/checks/validation/tag/invalid-edge-tags-check-regex-filter.json
- src/main/resources/org/openstreetmap/atlas/checks/validation/tag/invalid-tags-check-regex-filter.json
The following summaries the original issues reported by OSMOSE 5010.
Class 701 "Badly written word" : often a lack of accent on a capital letter (eg. Ecole for École)
http://osmose.openstreetmap.fr/en/map/#item=5010&zoom=17&lat=19.09385&lon=-72.699597&level=1&tags=&fixable=&issue_uuid=3574aad8-944c-39e6-101e-63d1aa7754fc
Class 703 "Word not found in dictionary" e.g. Cimetiere
http://osmose.openstreetmap.fr/en/map/#item=5010&zoom=17&lat=19.8516&lon=-73.19296&level=2&tags=&fixable=&issue_uuid=5e72073c-4361-60ff-d032-5b9cd7535f43
Class 704 "Encoding problem" : iso-* instead of utf-8 for example. e.g. ` instead of '
http://osmose.openstreetmap.fr/en/map/#item=5010&zoom=17&lat=43.698894&lon=7.25609&level=1&tags=&fixable=&issue_uuid=8f48285f-3b1c-89b9-302b-7c33da10d116
Class 803 "Name with …
> Orthograph Check - OSMOSE 5010

- gradle.properties
> Bump version to 6.3.2

- docs/available_checks.md
Just fix a typo in the available checks doc.
> Fix waterways doc link

- gradle.properties
version bump to 6.3.7 for atlas-checks release
rdar://90784454 (Luigi (3/28 - 4/1))
> 6.3.7 version bump

- gradle.properties
Version Bump to 6.3.8-SNAPSHOT
> Verison Bump

- gradle.properties
Version bump 6.3.10-SNAPSHOT
List potential impact to downstream libraries here (ex. atlas-checks, atlas-generator).
Describe unit tests being added with this PR.
Describe other (non-unit) test results here. In case of a new check or enhancements to existing 
checks, please add details on how many countries the check was tested on,
total flag counts, FP rate etc. (see below example).
|  ARE   |    109         |    33      |     30%       |   24 |   9 | 27%   |
> Version bump 6.3.10-SNAPSHOT

- gradle.properties
Version bump for next release.
> 6.3.11 Version Bump

- gradle.properties
Add a short description of the check here. Link any github issues associated with this PR.
List potential impact to downstream libraries here (ex. atlas-checks, atlas-generator).
Describe unit tests being added with this PR.
Describe other (non-unit) test results here. In case of a new check or enhancements to existing 
checks, please add details on how many countries the check was tested on,
total flag counts, FP rate etc. (see below example).
|  ARE   |    109         |    33      |     30%       |   24 |   9 | 27%   |
> version bump 6.3.12-SNAPSHOT

- docs/cluster.md
- docs/dev.md
- docs/fix_suggestions.md
- docs/maproulette_upload.md
- docs/tutorials/tutorial1-PoolSizeCheck.md
- docs/tutorials/tutorial2-OrphanNodeCheck.md
- docs/tutorials/tutorial3-SinkIslandCheck.md
This adds documentation for fix suggestions, and a few other minor doc updates.
> Documentation Updates

- config/configuration.json
- src/main/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheck.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheckTest.java
- src/test/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheckTestRule.java
Updating the instructions to better align with OSM codes of conduct around organized edits. 
No downstream impact
Updated a unit test for testing the instructions. 
The instruction shows up in MapRoulette as expected.
> AreasWithHighwayTagCheck Instructions Update

- gradle.properties
updating version as new change being introduced using AreasWithHighwayTagCheck Instructions Update #692
> version bump 6.3.13-SNAPSHOT
